# Generated by Django 4.2.15 on 2025-10-31 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miscore', '0001_initial'),
    ]

    operations = [
    ]
