# Generated by Django 4.2.15 on 2025-11-03 00:10

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miscore', '0002_listcourse_curriculumformanage_listcourserelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_no', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('requirement_type', models.CharField(choices=[('COMPULSORY', 'Bắt buộc'), ('ELECTIVE', 'Tự chọn')], max_length=20)),
                ('category', models.CharField(blank=True, default='', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listcourse_items', to='miscore.course')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listcourse_items', to='miscore.curriculum')),
            ],
            options={
                'verbose_name': 'học phần trong CTĐT',
                'verbose_name_plural': 'học phần trong CTĐT',
                'db_table': 'miscore_listcourse',
                'ordering': ('semester_no', 'course__code'),
            },
        ),
        migrations.CreateModel(
            name='CurriculumForManage',
            fields=[
            ],
            options={
                'verbose_name': 'Quản lý học phần CTĐT',
                'verbose_name_plural': 'Quản lý học phần CTĐT',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('miscore.curriculum',),
        ),
        migrations.CreateModel(
            name='Tuition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_credits', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=6, verbose_name='Tổng tín')),
                ('price_per_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giá / tín')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, verbose_name='Thành tiền')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Ghi chú')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
                ('curriculum', models.OneToOneField(db_column='curriculum_id', on_delete=django.db.models.deletion.CASCADE, related_name='tuition', to='miscore.curriculum')),
            ],
            options={
                'verbose_name': 'Học phí CTĐT',
                'verbose_name_plural': 'Học phí CTĐT',
                'db_table': 'miscore_tuition',
            },
        ),
        migrations.CreateModel(
            name='ListCourseRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('PREREQUISITE', 'Tiên quyết'), ('PREPARATORY', 'Học trước'), ('COREQUISITE', 'Song hành')], max_length=20)),
                ('course_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_from', to='miscore.listcourse')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='miscore.curriculum')),
                ('related_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_to', to='miscore.listcourse')),
            ],
            options={
                'verbose_name': 'quan hệ học phần',
                'verbose_name_plural': 'quan hệ học phần',
                'db_table': 'miscore_listcourserelation',
                'indexes': [models.Index(fields=['curriculum', 'course_item'], name='miscore_lis_curricu_79b083_idx'), models.Index(fields=['curriculum', 'related_item'], name='miscore_lis_curricu_9cd107_idx'), models.Index(fields=['curriculum', 'relation_type'], name='miscore_lis_curricu_f08364_idx')],
                'unique_together': {('curriculum', 'course_item', 'related_item', 'relation_type')},
            },
        ),
        migrations.AddIndex(
            model_name='listcourse',
            index=models.Index(fields=['curriculum', 'semester_no'], name='miscore_lis_curricu_4bd4d7_idx'),
        ),
        migrations.AddIndex(
            model_name='listcourse',
            index=models.Index(fields=['curriculum', 'requirement_type'], name='miscore_lis_curricu_eb573f_idx'),
        ),
        migrations.AddIndex(
            model_name='listcourse',
            index=models.Index(fields=['curriculum', 'category'], name='miscore_lis_curricu_eae558_idx'),
        ),
        migrations.AddIndex(
            model_name='listcourse',
            index=models.Index(fields=['course'], name='miscore_lis_course__a09bea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='listcourse',
            unique_together={('curriculum', 'course')},
        ),
    ]
