# Generated by Django 4.2.15 on 2026-05-15 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('miscore', '0003_listcourse_curriculumformanage_tuition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumCopyTool',
            fields=[
            ],
            options={
                'verbose_name': 'Sao chép CTĐT',
                'verbose_name_plural': 'Sao chép CTĐT',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('miscore.curriculum',),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Tên học phần'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('STUDENT', 'Sinh viên'), ('STAFF', 'Cán bộ/Giảng viên'), ('OFFICE', 'Phòng ban')], default='STUDENT', max_length=10, verbose_name='Vai trò')),
                ('dept', models.CharField(blank=True, default='', max_length=120, verbose_name='Khoa/Phòng')),
                ('idcode', models.CharField(blank=True, default='', max_length=50, verbose_name='Mã định danh (MSSV/Mã CB)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Hồ sơ tài khoản',
                'verbose_name_plural': 'Hồ sơ tài khoản',
                'db_table': 'miscore_profile',
            },
        ),
    ]
