-- lecturers_upsert_pg.sql
-- Upsert danh sách giảng viên. Yêu cầu bảng miscore_faculty đã có dữ liệu.

WITH src(name, position, email, phone, faculty_name) AS (
  VALUES

('PGS.TS. Đào Văn Dương','Phó hiệu trưởng; Trưởng Khoa; Trưởng nhóm nghiên cứu mạnh','duong.daovan@phenikaa-uni.edu.vn','+84690004618','Khoa Công nghệ sinh học, Hóa học và Kỹ thuật môi trường'),
('TS. Vũ Ngọc Phan','Phó trưởng khoa; Giảng viên','phan.vungoc@phenikaa-uni.edu.vn','+84535512033','Khoa Công nghệ sinh học, Hóa học và Kỹ thuật môi trường'),
('TS. Nguyễn Hồng Minh','Phó Trưởng khoa; Giảng viên; Giám đốc Trung tâm Nguồn gen','minh.nguyenhong@phenikaa-uni.edu.vn','+84473484163','Khoa Công nghệ sinh học, Hóa học và Kỹ thuật môi trường'),
('GS.TSKH. Trần Vĩnh Diệu','Giảng viên cao cấp','tranvinhdieuplm@gmail.com','+84906212994','Khoa Công nghệ sinh học, Hóa học và Kỹ thuật môi trường'),
('PGS.TS. Phan Thị Minh Ngọc','Giảng viên cao cấp','Ptminhngoc18@gmail.com','+84992389797','Khoa Công nghệ sinh học, Hóa học và Kỹ thuật môi trường'),
('PGS.TS. Tạ Thị Phương Hòa','Giảng viên cao cấp','taphuonghoa@gmail.com','+84583736355','Khoa Công nghệ sinh học, Hóa học và Kỹ thuật môi trường'),
('TS. Phạm Anh Tuấn','Giảng viên','tuan.phamanh@phenikaa-uni.edu.vn','+84350239771','Khoa Công nghệ sinh học, Hóa học và Kỹ thuật môi trường'),
('TS Ngô Thị Thúy Hường','Giảng viên','huong.ngothithuy@phenikaa-uni.edu.vn','+84402361752','Khoa Công nghệ sinh học, Hóa học và Kỹ thuật môi trường'),
('TS. Đỗ Thị Liên','Giảng viên','lien.dothi@phenikaa-uni.edu.vn','+84391382092','Khoa Công nghệ sinh học, Hóa học và Kỹ thuật môi trường'),
('TS. Vũ Ngọc Hùng','Giảng viên','hung.vungoc@phenikaa-uni.edu.vn','+84977269945','Khoa Công nghệ sinh học, Hóa học và Kỹ thuật môi trường'),
('TS. Nguyễn Tiến Khí','Giảng viên','khi.nguyentien@phenikaa-uni.edu.vn','+84850281002','Khoa Công nghệ sinh học, Hóa học và Kỹ thuật môi trường'),
('TS. Trần Văn Tân','Giảng viên','tan.tranvan@phenikaa-uni.edu.vn','+84776018698','Khoa Công nghệ sinh học, Hóa học và Kỹ thuật môi trường'),
('TS Vũ Thị Hồng Hà','Giảng viên','ha.vuthihong@phenikaa-uni.edu.vn','+84697611636','Khoa Công nghệ sinh học, Hóa học và Kỹ thuật môi trường'),
('TS. Đặng Viết Quang','Giảng viên','quang.dangviet@phenikaa-uni.edu.vn','+84916542323','Khoa Công nghệ sinh học, Hóa học và Kỹ thuật môi trường'),
('TS. Phạm Thị Lan Hương','Giảng viên','huong.phamthilan@phenikaa-uni.edu.vn','+84395181521','Khoa Công nghệ sinh học, Hóa học và Kỹ thuật môi trường'),
('TS. Nguyễn Tăng Sơn','Giảng viên','son.nguyentang@phenikaa-uni.edu.vn','+84711161925','Khoa Công nghệ sinh học, Hóa học và Kỹ thuật môi trường'),
('TS. Lê Thanh Thảo','Giảng viên','thao.lethanh@phenikaa-uni.edu.vn','+84892865950','Khoa Công nghệ sinh học, Hóa học và Kỹ thuật môi trường'),
('ThS. Đinh Thị Ngọc Mai','Giảng viên','mai.dinhthingoc@phenikaa-uni.edu.vn','+84631313472','Khoa Công nghệ sinh học, Hóa học và Kỹ thuật môi trường'),
('TS. Trần Hữu Phong','Giảng viên','phong.tranhuu@phenikaa-uni.edu.vn','+84480898779','Khoa Công nghệ sinh học, Hóa học và Kỹ thuật môi trường'),
('TS. Phạm Thị Lánh','Giảng viên','lanh.phamthi@phenikaa-uni.edu.vn','+84418081475','Khoa Công nghệ sinh học, Hóa học và Kỹ thuật môi trường'),
('TS. Nguyễn Thị Hạnh Tiên','Giảng ciên','tien.nguyenthihanh@phenikaa-uni.edu.vn','+84336696611','Khoa Công nghệ sinh học, Hóa học và Kỹ thuật môi trường'),
('TS. Hà Thu Hường','Giảng viên','huong.hathu@phenikaa.com','+84421822808','Khoa Công nghệ sinh học, Hóa học và Kỹ thuật môi trường'),
('TS. Hoàng Văn Tuấn','Nghiên cứu viên; Giảng viên','tuan.hoangvan@phenikaa-uni.edu.vn','+84439156866','Khoa Công nghệ sinh học, Hóa học và Kỹ thuật môi trường'),
('TS. Nguyễn Thị Thu Thủy','Nghiên cứu viên; Giảng viên','thuy.nguyenthithu@phenikaa-uni.edu.vn','+84662279728','Khoa Công nghệ sinh học, Hóa học và Kỹ thuật môi trường'),
('TS. Nguyễn Thị Minh Thanh','Giảng viên','thanh.nguyenthiminh@phenikaa-uni.edu.vn','+84850365529','Khoa Công nghệ sinh học, Hóa học và Kỹ thuật môi trường'),
('TS. Phạm Thùy Dương','Giảng viên','duong.phamthuy@phenikaa-uni.edu.vn','+84314815240','Khoa Công nghệ sinh học, Hóa học và Kỹ thuật môi trường'),
('TS. Bùi Hoàng Linh','Giảng viên','linh.buihoang@phenikaa-uni.edu.vn','+84652288743','Khoa Công nghệ sinh học, Hóa học và Kỹ thuật môi trường'),
('CN. Nguyễn Thị Thuận','Giáo vụ khoa','thuan.nguyenthi@phenikaa-uni.edu.vn','+84659409092','Khoa Công nghệ sinh học, Hóa học và Kỹ thuật môi trường'),
('CN. Nguyễn Thị Khánh Huyền','Giáo vụ khoa','huyen.nguyenthikhanh1@phenikaa-uni.edu.vn','+84730131901','Khoa Công nghệ sinh học, Hóa học và Kỹ thuật môi trường'),

('GS.TS. Trần Đức Tân','Trưởng khoa; Trưởng nhóm nghiên cứu tiềm năng','tan.tranduc@phenikaa-uni.edu.vn','+84904182389','Khoa Điện - Điện tử'),
('TS. Lương Văn Sử','Phó trưởng khoa','su.luongvan@phenikaa-uni.edu.vn','+84986235122','Khoa Điện - Điện tử'),
('PGS. TS. Nguyễn Trọng Thắng','Phó trưởng khoa','thang.nguyentrong@phenikaa-uni.edu.vn','+84388468555','Khoa Điện - Điện tử'),
('TS. Bùi Văn Hào','Trợ lý Hiệu trưởng; Trưởng nhóm nghiên cứu tiềm năng','hao.buivan@phenikaa-uni.edu.vn','+84868015368','Khoa Điện - Điện tử'),
('TS. Dương Chính Cương','Phó trưởng phòng Đào tạo và Quản lý sinh viên','cuong.duongchinh@phenikaa-uni.edu.vn','+84915780866','Khoa Điện - Điện tử'),
('TS. Hoàng Quang Trung','Giảng viên','trung.hoangquang@phenikaa-uni.edu.vn','+84865070280','Khoa Điện - Điện tử'),
('PGS. TS. Vũ Ngọc Hải','Trợ lí Tổng giám đốc; Giảng viên','hai.vungoc@phenikaa-uni.edu.vn','+84934682025','Khoa Điện - Điện tử'),
('PGS. TS. Trần Xuân Kiên','Giảng viên','kien.tranxuan@phenikaa-uni.edu.vn','+84983887496','Khoa Điện - Điện tử'),
('TS. Nguyễn Ngọc Việt','Giảng viên/Nghiên cứu viên','viet.nguyenngoc@phenikaa-uni.edu.vn','+84962344273','Khoa Điện - Điện tử'),
('TS. Nguyễn Hữu Tuân','Giảng viên/Nghiên cứu viên','tuan.nguyenhuu@phenikaa-uni.edu.vn','+84824456448','Khoa Điện - Điện tử'),
('TS. Lê Viết Thông','Giảng viên/Nghiên cứu viên','thong.leviet@phenikaa-uni.edu.vn','+84963703950','Khoa Điện - Điện tử'),
('TS. Lê Minh Huy','Giảng viên/Nghiên cứu viên','huy.leminh@phenikaa-uni.edu.vn','+84327764631','Khoa Điện - Điện tử'),
('TS. Trần Huy Hùng','Giảng viên/Nghiên cứu viên','hung.tranhuy@phenikaa-uni.edu.vn','+84972242810','Khoa Điện - Điện tử'),
('TS. Nguyễn Văn Tới','Giảng viên/Nghiên cứu viên','toi.nguyenvan@phenikaa-uni.edu.vn','+84867536913','Khoa Điện - Điện tử'),
('TS. Nguyễn Ngọc Nam','Giảng viên/Nghiên cứu viên','nam.nguyenngoc@phenikaa-uni.edu.vn','+84879218121','Khoa Điện - Điện tử'),
('ThS. Vũ Hoàng Diệu','Giảng viên/Nghiên cứu viên','dieu.vuhoang@phenikaa-uni.edu.vn','+84842116568','Khoa Điện - Điện tử'),
('TS. Nguyễn Thị Thanh Vân','Giảng viên/Nghiên cứu sinh','van.nguyenthithanh@phenikaa-uni.edu.vn','+84836779233','Khoa Điện - Điện tử'),
('TS. Nguyễn Ngọc Thanh','Giảng viên/Nghiên cứu viên','thanh.nguyenngoc@phenikaa-uni.edu.vn','+84926703999','Khoa Điện - Điện tử'),
('TS. Lê Văn Thuận','Giảng viên/Nghiên cứu viên','thuan.levan@phenikaa-uni.edu.vn','+84987159386','Khoa Điện - Điện tử'),
('TS. Nguyễn Đắc Cử','Giảng viên/Nghiên cứu viên','cu.nguyendac@phenikaa-uni.edu.vn','+84375355155','Khoa Điện - Điện tử'),
('ThS. Phạm Quang Vượng','Giảng viên/Nghiên cứu sinh Tiến sỹ','vuong.phamquang@phenikaa-uni.edu.vn','+84899488466','Khoa Điện - Điện tử'),
('ThS. Đào Tô Hiệu','Giảng viên/Nghiên cứu viên/Nghiên cứu sinh Tiến sỹ','hieu.daoto@phenikaa-uni.edu.vn','+84389959524','Khoa Điện - Điện tử'),
('TS. Nguyễn Tràng Tiến','Giảng viên/Nghiên cứu viên','tien.nguyentrang@phenikaa-uni.edu.vn','+84565859515','Khoa Điện - Điện tử'),
('TS. Nguyễn Viết Chiến','Giảng viên/Nghiên cứu viên','chien.nguyenviet@phenikaa-uni.edu.vn','+84976482619','Khoa Điện - Điện tử'),
('TS. Nguyễn Thị Thanh Quỳnh','Giảng viên/Nghiên cứu viên','quynh.nguyenthithanh@phenikaa-uni.edu.vn','+84889368333','Khoa Điện - Điện tử'),
('TS. Phạm Văn Thiêm','Trưởng bộ môn Tự động hóa và điện tử thông minh; Giảng viên/Nghiên cứu viên','thiem.phamvan@phenikaa-uni.edu.vn','+84981332238','Khoa Điện - Điện tử'),
('PGS. TS. Nguyễn Đức Trung Kiên','Giảng viên/Nghiên cứu viên','kien.nguyenductrung@phenikaa-uni.edu.vn','+84912201194','Khoa Điện - Điện tử'),
('TS. Lê Thái Hà','Giám đốc Trung tâm đào tạo thiết kế vi mạch bán dẫn','ha.lethai@phenikaa-uni.edu.vn','+84868817174','Khoa Điện - Điện tử'),
('TS. Vũ Quốc Đông','Giảng viên/Nghiên cứu viên','dong.vuquoc@phenikaa-uni.edu.vn','+84917369808','Khoa Điện - Điện tử'),
('TS. Bạch Sỹ Hưng','Giảng viên/Nghiên cứu viên','hung.bachsy@phenikaa-uni.edu.vn','+84923069345','Khoa Điện - Điện tử'),
('ThS. Nguyễn Tuấn Anh','Giảng viên thực hành/ Thạc sỹ','anh.nguyentuan3@phenikaa-uni.edu.vn','+84329681997','Khoa Điện - Điện tử'),
('ThS. Bùi Thị Cúc','Giảng viên/Nghiên cứu viên','cuc.buithi@phenikaa-uni.edu.vn','+84934226268','Khoa Điện - Điện tử'),
('ThS. Đinh Văn Nam','Giảng viên/Nghiên cứu viên','nam.dinhvan@phenikaa-uni.edu.vn','+84988999027','Khoa Điện - Điện tử'),
('ThS. Đoàn Diệu Huyền','Giáo vụ Khoa','huyen.doandieu@phenikaa-uni.edu.vn','+84988820808','Khoa Điện - Điện tử'),
('Mrs. Mai Thị Minh','Giáo vụ Khoa','minh.maithi@phenikaa-uni.edu.vn','+84978971640','Khoa Điện - Điện tử'),
('ThS. Nguyễn Thiên Thịnh','Kỹ thuật viên; Giảng viên thực hành','thinh.nguyenthien@phenikaa-uni.edu.vn','+84986206715','Khoa Điện - Điện tử'),
('Mr. Đào Minh Thành','Kỹ thuật viên; Giảng viên thực hành','thanh.daominh@phenikaa-uni.edu.vn','+84974941635','Khoa Điện - Điện tử'),
('Ms. Phan Hiền Anh','Quản lý lớp chuyên nghiệp','anh.phanhien@phenikaa-uni.edu.vn','+84981263588','Khoa Điện - Điện tử'),

('PGS. TS. Vũ Lê Huy','Trưởng Khoa','huy.vule@phenikaa-uni.edu.vn','+840912541514','Khoa Cơ khí - Cơ điện tử'),
('TS. Ngô Văn Lực','Phó Trưởng Khoa; Trưởng CTĐT Kỹ thuật cơ khí','luc.ngovan@phenikaa-uni.edu.vn','+840982900248','Khoa Cơ khí - Cơ điện tử'),
('TS. Nguyễn Văn Tuấn','Phó Trưởng Khoa','tuan.nguyenvan1@phenikaa-uni.edu.vn','+840904996848','Khoa Cơ khí - Cơ điện tử'),
('TS. Nguyễn Đình Dũng','Giảng viên','dung.nguyendinh@phenikaa-uni.edu.vn','+840985905768','Khoa Cơ khí - Cơ điện tử'),
('TS. Vũ Thị Liên','Giảng viên','lien.vuthi@phenikaa-uni.edu.vn','+840936536154','Khoa Cơ khí - Cơ điện tử'),
('PGS. TS. Trần Vĩnh Hưng','Giảng viên','hung.tranvinh@phenikaa-uni.edu.vn','+84724854339','Khoa Cơ khí - Cơ điện tử'),
('TS. Nguyễn Như Hiếu','Giảng viên','hieu.nguyennhu@phenikaa-uni.edu.vn','+84479352272','Khoa Cơ khí - Cơ điện tử'),
('TS. Trần Ngọc An','Giảng viên','an.tranngoc@phenikaa-uni.edu.vn','+84960155248','Khoa Cơ khí - Cơ điện tử'),
('ThS. Khổng Minh','Giảng viên','minh.khong@phenikaa-uni.edu.vn','+84466570767','Khoa Cơ khí - Cơ điện tử'),
('TS. Nguyễn Đức Nam','Giảng viên; Trưởng CTĐT Kỹ thuật cơ điện tử','nam.nguyenduc@phenikaa-uni.edu.vn','+840977570912','Khoa Cơ khí - Cơ điện tử'),
('TS. Nguyễn Văn Hải','Giảng viên','hai.nguyenvan1@phenikaa-uni.edu.vn','+840987868429','Khoa Cơ khí - Cơ điện tử'),
('TS. Lê Tiến Thịnh','Giảng viên','thinh.letien@phenikaa-uni.edu.vn','+840902889339','Khoa Cơ khí - Cơ điện tử'),
('TS. Trần Quốc Quân','Giảng viên','quan.tranquoc@phenikaa-uni.edu.vn','+84606705776','Khoa Cơ khí - Cơ điện tử'),
('TS. Đỗ Quang Chấn','Giảng viên','chan.doquang@phenikaa-uni.edu.vn','+840983992081','Khoa Cơ khí - Cơ điện tử'),
('TS. Đinh Thế Hưng','Giảng viên','hung.dinhthe@phenikaa-uni.edu.vn','+840971617099','Khoa Cơ khí - Cơ điện tử'),
('ThS. Lê Văn Phong','Giảng viên','phong.levan@phenikaa-uni.edu.vn','+840364510899','Khoa Cơ khí - Cơ điện tử'),
('TS. Trần Ngọc Giang','Giảng viên','giang.tranngoc@phenikaa-uni.edu.vn','+840987300394','Khoa Cơ khí - Cơ điện tử'),
('TS. Đặng Văn Hiếu','Giảng viên','hieu.dangvan@phenikaa-uni.edu.vn','+840947066013','Khoa Cơ khí - Cơ điện tử'),
('TS. Đỗ Anh Tú','Giảng viên','tu.doanh@phenikaa-uni.edu.vn','+840989573836','Khoa Cơ khí - Cơ điện tử'),
('ThS. Nguyễn Văn Long','Giảng viên','long.nguyenvan@phenikaa-uni.edu.vn','+840904173695','Khoa Cơ khí - Cơ điện tử'),
('TS. Phạm Văn Hiệp','Giảng viên','hiep.phamvan@phenikaa-uni.edu.vn','+840969660534','Khoa Cơ khí - Cơ điện tử'),
('Ms. Vũ Thị Trang','Giáo vụ Khoa','trang.vuthi@phenikaa-uni.edu.vn','+840983896465','Khoa Cơ khí - Cơ điện tử'),

('PGS.TS. Phương Đình Tâm','Trưởng Khoa (Dean of Faculty)','tam.phuongdinh@phenikaa-uni.edu.vn','+84906158386','Khoa Khoa học và Kỹ thuật vật liệu'),
('TS. Phan Đức Anh','Phó trưởng khoa (Vice Dean of Faculty); Trưởng nhóm nghiên cứu','anh.phanduc@phenikaa-uni.edu.vn','+84978346461','Khoa Khoa học và Kỹ thuật vật liệu'),
('TS. Nguyễn Viết Hương','Phó trưởng khoa (Vice Dean of Faculty)','huong.nguyenviet@phenikaa-uni.edu.vn','+84972984369','Khoa Khoa học và Kỹ thuật vật liệu'),
('GS.TS. Phạm Thành Huy','Phó Tổng Giám đốc (Deputy General Director); Trưởng nhóm nghiên cứu mạnh','huy.phamthanh@phenikaa-uni.edu.vn','+84369153312','Khoa Khoa học và Kỹ thuật vật liệu'),
('GS.TS. Lê Anh Tuấn','Trưởng nhóm nghiên cứu mạnh; Giảng viên','tuan.leanh@phenikaa-uni.edu.vn','+84853571385','Khoa Khoa học và Kỹ thuật vật liệu'),
('GS.TS. Đỗ Vân Nam','Trưởng nhóm nghiên cứu; Giảng viên','nam.dovan@phenikaa-uni.edu.vn','+84833662838','Khoa Khoa học và Kỹ thuật vật liệu'),
('PGS.TS. Dương Anh Tuấn','Giảng viên','tuan.duonganh@phenikaa-uni.edu.vn','+84906030096','Khoa Khoa học và Kỹ thuật vật liệu'),
('PGS.TS. Lê Mạnh Tú','Giảng viên','tu.lemanh@phenikaa-uni.edu.vn','+84947339009','Khoa Khoa học và Kỹ thuật vật liệu'),
('TS. Đặng Thế Hùng','Trưởng nhóm nghiên cứu tiềm năng','hung.dangthe@phenikaa-uni.edu.vn','+84342592093','Khoa Khoa học và Kỹ thuật vật liệu'),
('TS. Nguyễn Ngọc Lĩnh','Giảng viên','linh.nguyengoc@phenikaa-uni.edu.vn','+849823000744','Khoa Khoa học và Kỹ thuật vật liệu'),
('TS. Nghiêm Thị Minh Hòa','Giảng viên','hoa.nghiemthiminh@phenikaa-uni.edu.vn','+84342718913','Khoa Khoa học và Kỹ thuật vật liệu'),
('TS. Hoàng Như Vân','Giảng viên','van.hoangnhu@phenikaa-uni.edu.vn','+84948791819','Khoa Khoa học và Kỹ thuật vật liệu'),
('TS. Đinh Thị Hinh','Giảng viên','hinh.dinhthi@phenikaa-uni.edu.vn','+84354212986','Khoa Khoa học và Kỹ thuật vật liệu'),
('TS. Trần Mạnh Trung','Giảng viên','trung.tranmanh@phenikaa-uni.edu.vn','+84947609189','Khoa Khoa học và Kỹ thuật vật liệu'),
('TS. Nguyễn Minh Hiếu','Giảng viên','hieu.nguyenminh@phenikaa-uni.edu.vn','+849046024013','Khoa Khoa học và Kỹ thuật vật liệu'),
('TS. Trần Nguyễn Minh Anh','Giảng viên','anh.trannguyenminh@phenikaa-uni.edu.vn','+84384505993','Khoa Khoa học và Kỹ thuật vật liệu'),
('KS. Nguyễn Đình Nam','Kỹ thuật viên - Trợ giảng','nam.nguyendinh@phenikaa-uni.edu.vn','+84945005309','Khoa Khoa học và Kỹ thuật vật liệu'),
('CN. Đỗ Thị Hòa','Giáo vụ Khoa','hoa.dothi@phenikaa-uni.edu.vn','+84378505387','Khoa Khoa học và Kỹ thuật vật liệu'),

('PGS.TS . Trần Quang Vinh','Trưởng Khoa','vinh.tranquang@phenikaa-uni.edu.vn','+84427898874','Khoa Kỹ thuật Ô tô và Năng lượng'),
('TS. Trần Anh Trung','Phó trưởng Khoa','trung.trananh@phenikaa-uni.edu.vn','+84543817492','Khoa Kỹ thuật Ô tô và Năng lượng'),
('TS. Nguyễn Trung Kiên','Phó trưởng Khoa','Kien.nguyentrung@phenikaa-uni.edu.vn','+84573050644','Khoa Kỹ thuật Ô tô và Năng lượng'),
('TS. Nguyễn Duy Vinh','Giám đôc chương trình đào tạo','vinh.nguyenduy@phenikaa-uni.edu.vn','+84694036499','Khoa Kỹ thuật Ô tô và Năng lượng'),
('PGS. TS. Hồ Xuân Năng','Giảng viên','nang.hoxuan@phenikaa-uni.edu.vn','+84842264741','Khoa Kỹ thuật Ô tô và Năng lượng'),
('GS.TS. Vũ Văn Trường','Giảng viên; Trưởng nhóm nghiên cứu mạnh','truong.vuvan@phenikaa-uni.edu.vn','+84823676559','Khoa Kỹ thuật Ô tô và Năng lượng'),
('PGS.TS. Nguyễn Phú Khánh','Giảng viên','khanh.nguyenphu@phenikaa-uni.edu.vn','+84715420244','Khoa Kỹ thuật Ô tô và Năng lượng'),
('TS. Lê Anh Sơn','Giảng viên','son.leanh@phenikaa.com','+84646944614','Khoa Kỹ thuật Ô tô và Năng lượng'),
('PGS.TS. Hoàng Đình Long','Giảng viên','Long.hoangdinh@phenikaa-uni.edu.vn','+84805296419','Khoa Kỹ thuật Ô tô và Năng lượng'),
('TS. Nguyễn Tiến Cường','Giảng viên','cuong.nguyentien@phenikaa-uni.edu.vn','+84815978667','Khoa Kỹ thuật Ô tô và Năng lượng'),
('ThS. Trương Văn Thuận','Giảng viên','Thuan.truongvan@phenikaa-uni.edu.vn','+84617704835','Khoa Kỹ thuật Ô tô và Năng lượng'),
('ThS. Nguyễn Mạnh Long','Giảng viên','Long.nguyenmanh@phenikaa-uni.edu.vn','+84736276667','Khoa Kỹ thuật Ô tô và Năng lượng'),
('ThS. Bùi Nhật Huy','Giảng viên','huy.buinhat@phenikaa-uni.edu.vn','+84906333684','Khoa Kỹ thuật Ô tô và Năng lượng'),
('TS. Phạm Duy Bính','Giảng viên','binh.phamduy@phenikaa-uni.edu.vn','+84874238419','Khoa Kỹ thuật Ô tô và Năng lượng'),
('ThS. Vũ Văn Hưng','Giảng viên','Hung.vuvan@phenikaa-uni.edu.vn','+84558534705','Khoa Kỹ thuật Ô tô và Năng lượng'),
('ThS. Nguyễn Văn Du','Giảng viên','du.nguyenvan1@phenikaa-uni.edu.vn','+84xxxxxxxxx','Khoa Kỹ thuật Ô tô và Năng lượng'),
('ThS. Nguyễn Như Thành','Giảng viên','thanh.nguyennhup@phenikaa-uni.edu.vn','+84xxxxxxxxx','Khoa Kỹ thuật Ô tô và Năng lượng'),
('TS. Phạm Văn Thoan','Giảng viên','thoan.phamvan@phenikaa-uni.edu.vn','+84723960514','Khoa Kỹ thuật Ô tô và Năng lượng'),
('GS.TS. Phạm Minh Tuấn','Giảng viên','tuan.phamminh@phenikaa-uni.edu.vn','+84381665897','Khoa Kỹ thuật Ô tô và Năng lượng'),
('TS. Nguyễn Văn Hải','Giảng viên','Hai.nguyenvan@phenikaa-uni.edu.vn','+84988513791','Khoa Kỹ thuật Ô tô và Năng lượng'),
('ThS. Nguyễn Thị Thanh Huyền','Thư ký khoa','huyen.nguyenthithanh1@phenikaa-uni.edu.vn','+84895237986','Khoa Kỹ thuật Ô tô và Năng lượng'),
('ThS. Lương Kim Oanh','Thư ký khoa','Oanh.luongkim@phenikaa-uni.edu.vn','+84790159981','Khoa Kỹ thuật Ô tô và Năng lượng'),
('TS. Nguyễn Đình Hoè','Trợ lỹ nghiên cứu','hoe.nguyendinh@phenikaa-uni.edu.vn','+84326970568','Khoa Kỹ thuật Ô tô và Năng lượng'),
('TS. Nguyễn Tuấn Vinh','Trợ lý nghiên cứu','vinh.nguyentuan@phenikaa-uni.edu.vn','+84898255975','Khoa Kỹ thuật Ô tô và Năng lượng'),

('PGS.TS. Ngô Hồng Sơn','Trưởng khoa','son.ngohong@phenikaa-uni.edu.vn','+84958016489','Khoa Hệ thống thông tin'),
('TS. Mai Xuân Tráng','Phó Trưởng khoa','trang.maixuan@phenikaa-uni.edu.vn','+84490240604','Khoa Hệ thống thông tin'),
('TS. Phạm Ngọc Hưng','Phó Trưởng khoa','hung.phamngoc@phenikaa-uni.edu.vn','+84451124964','Khoa Hệ thống thông tin'),
('PGS.TS. Lê Văn Vinh','Giảng viên, Trưởng nhóm nghiên cứu','vinh.levan@phenikaa-uni.edu.vn','+84304660430','Khoa Hệ thống thông tin'),
('PGS.TS. Phạm Tuấn Minh','Giảng viên','minh.phamtuan@phenikaa-uni.edu.vn','+84860506774','Khoa Hệ thống thông tin'),
('TS. Lê Hoàng Anh','Giám đốc Trung tâm Công nghệ thông tin','anh.lehoang@phenikaa-uni.edu.vn','+84955724951','Khoa Hệ thống thông tin'),
('TS. Nguyễn Công Lượng','Giảng viên, Trưởng nhóm nghiên cứu','luong.nguyencong@phenikaa-uni.edu.vn','+84479422679','Khoa Hệ thống thông tin'),
('PGS.TS. Phạm Tiến Lâm','Giảng viên, Giám đốc CTĐT Khoa học máy tính; CTĐT Trí tuệ nhân tạo','lam.phamtien@phenikaa-uni.edu.vn','+84481677890','Khoa Trí tuệ nhân tạo'),
('PGS. TS. Phạm Văn Cảnh','Giảng viên, Giám đốc CTĐT TN KHMT; ThS KHMT','canh.phamvan@phenikaa-uni.edu.vn','+84784500994','Khoa Khoa học máy tính'),
('TS. Trịnh Thanh Bình','Giảng viên, Giám đốc CTĐT Kỹ thuật phần mềm','binh.trinhthanh@phenikaa-uni.edu.vn','+84808101287','Khoa Hệ thống thông tin'),
('ThS. Nguyễn Thành Trung','Giảng viên, Giám đốc CTĐT CNTT Việt-Nhật','trung.nguyenthanh@phenikaa-uni.edu.vn','+84782901820','Khoa Hệ thống thông tin'),
('ThS. Vũ Thị Ngọc Anh','Giảng viên, Chủ tịch Công đoàn Khoa','anh.vuthingoc1@phenikaa-uni.edu.vn','+84478015466','Khoa Hệ thống thông tin'),
('TS. Tạ Thúy Anh','Giảng viên','anh.tathuy@phenikaa-uni.edu.vn','+84570606505','Khoa Hệ thống thông tin'),
('TS. Nguyễn Văn Duy','Giảng viên/Postdoc','duy.nguyenvan@phenikaa-uni.edu.vn','+84616645090','Khoa Hệ thống thông tin'),
('TS. Trần Đăng Hoan','Giảng viên - Nghiên cứu viên','hoan.trandang@phenikaa-uni.edu.vn','+84411602647','Khoa Hệ thống thông tin'),
('TS. Trịnh Thành','Giảng viên','thanh.trinh@phenikaa-uni.edu.vn','+84501641973','Khoa Hệ thống thông tin'),
('TS. Đoàn Trung Sơn','Giảng viên, Giám đốc CTĐT An toàn thông tin','son.doantrung@phenikaa-uni.edu.vn','+84939493167','Khoa Hệ thống thông tin'),
('TS. Dương Thị Kim Huyền','Giảng viên','huyen.duongthikim@phenikaa-uni.edu.vn','+84434521122','Khoa Hệ thống thông tin'),
('TS. Nguyễn Thị Thùy Liên','Giảng viên, Giám đốc CTĐT Công nghệ thông tin','lien.nguyenthithuy@phenikaa-uni.edu.vn','+84371178166','Khoa Hệ thống thông tin'),
('ThS. Vũ Văn Quang','Giảng viên','quang.vuvan@phenikaa-uni.edu.vn','+84749649018','Khoa Hệ thống thông tin'),
('ThS. Nguyễn Minh Anh','Giảng viên - Nghiên cứu viên','anh.nguyenminh@phenikaa-uni.edu.vn','+84876022257','Khoa Hệ thống thông tin'),
('ThS. Phạm Hoàng Giang','Giảng viên - Nghiên cứu viên','giang.phamhoang@phenikaa-uni.edu.vn','+84617163164','Khoa Hệ thống thông tin'),
('TS. Phạm Văn Hà','Giảng viên','ha.phamvan@phenikaa-uni.edu.vn','+84594972048','Khoa Hệ thống thông tin'),
('ThS. Nguyễn Văn Thiệu','Giảng viên','thieu.nguyenvan@phenikaa-uni.edu.vn','+84329165154','Khoa Hệ thống thông tin'),
('ThS. Nguyễn Văn Cường','Giảng viên','cuong.nguyenvan@phenikaa-uni.edu.vn','+84690365565','Khoa Hệ thống thông tin'),
('ThS. La Văn Quân','Giảng viên','quan.lavan@phenikaa-uni.edu.vn','+84792170825','Khoa Hệ thống thông tin'),
('TS. Bùi Huy Toàn','Giảng viên','toan.buihuy@phenikaa-uni.edu.vn','+84891480075','Khoa Hệ thống thông tin'),
('TS. Đặng Thị Thuý An','Giảng viên','an.dangthithuy@phenikaa-uni.edu.vn','+84803801213','Khoa Hệ thống thông tin'),
('TS. Mai Thuý Nga','Giảng viên','nga.maithuy@phenikaa-uni.edu.vn','+84884670887','Khoa Hệ thống thông tin'),
('ThS. Nguyễn Thị Khánh Trâm','Giảng viên','tram.nguyenthikhanh@phenikaa-uni.edu.vn','+84701387862','Khoa Hệ thống thông tin'),
('TS. Nguyễn Lệ Thu','Giảng viên','thu.nguyenle1@phenikaa-uni.edu.vn','+84337893751','Khoa Hệ thống thông tin'),
('TS. Nguyễn Thanh Bình','Giảng viên','binh.nguyenthanh@phenikaa-uni.edu.vn','+84786165533','Khoa Hệ thống thông tin'),
('ThS. Phạm Trung Dũng','Giảng viên','dung.phamtrung@phenikaa-uni.edu.vn','+84402646969','Khoa Hệ thống thông tin'),
('ThS. Vũ Quang Dũng','Giảng viên','dung.vuquang@phenikaa-uni.edu.vn','+84730621279','Khoa Hệ thống thông tin'),
('ThS. Nguyễn Văn Sơn','Giảng viên','son.nguyenvan@phenikaa-uni.edu.vn','+84993576546','Khoa Hệ thống thông tin'),
('TS. Nguyễn Thị Vân','Giảng viên','van.nguyenthi1@phenikaa-uni.edu.vn','+84967480787','Khoa Hệ thống thông tin'),
('ThS. Nguyễn Hữu Đạt','Giảng viên, Bí thư Đoàn TN Trường','dat.nguyenhuu@phenikaa-uni.edu.vn','+84773502811','Khoa Hệ thống thông tin'),
('TS. Đỗ Quốc Trường','Giảng viên','truong.doquoc@phenikaa-uni.edu.vn','+84507359411','Khoa Hệ thống thông tin'),
('ThS. Phạm Kim Thành','Giảng viên','thanh.phamkim@phenikaa-uni.edu.vn','+84942270182','Khoa Hệ thống thông tin'),
('ThS. Nguyễn Xuân Quế','Giảng viên','que.nguyenxuan@phenikaa-uni.edu.vn','+84591275190','Khoa Hệ thống thông tin'),
('ThS. Nguyễn Thị Dinh','Giảng viên','dinh.nguyenthi@phenikaa-uni.edu.vn','+84703810796','Khoa Hệ thống thông tin'),
('ThS. NCS. Nguyễn Anh Tuấn','Giảng viên','tuan.nguyenanh2@phenikaa-uni.edu.vn','+84542401875','Khoa Hệ thống thông tin'),
('ThS. Đặng Thị Ngoan','Giảng viên','ngoan.thidang@phenikaa-uni.edu.vn','+84795720428','Khoa Hệ thống thông tin'),
('ThS. Lương Tùng Dương','Giảng viên','duong.luongtung@phenikaa-uni.edu.vn','+84753979414','Khoa Hệ thống thông tin'),
('ThS. Nguyễn Ngọc Hùng','Giảng viên','hung.ngocnguyen@phenikaa-uni.edu.vn','+84360830729','Khoa Hệ thống thông tin'),
('ThS. Vũ Thị Kiều Anh','Giảng viên','anh.vuthikieu@phenikaa-uni.edu.vn','+84760519259','Khoa Hệ thống thông tin'),
('TS. Nguyễn Ngọc Giang','Giảng viên','giang.nguyenngoc@phenikaa-uni.edu.vn','+84435297403','Khoa Hệ thống thông tin'),
('TS. Nguyễn Kim Tuấn','Giảng viên','tuan.nguyenkim@phenikaa-uni.edu.vn','+84643788765','Khoa Hệ thống thông tin'),
('ThS. Bùi Anh Tuấn','Giảng viên, Phó Bí thư Đoàn TN Trường','tuan.buianh@phenikaa-uni.edu.vn','+84819106698','Khoa Hệ thống thông tin'),
('CN. Nguyễn Thị Ngọc Lan','Giáo vụ','lan.nguyenthingoc@phenikaa-uni.edu.vn','+84303040587','Khoa Hệ thống thông tin'),
('CN. Vũ Thị Huyền','Giáo vụ','huyen.vuthi@phenikaa-uni.edu.vn','+84993800549','Khoa Hệ thống thông tin'),

('TS. Đào Trung Kiên','Trưởng Khoa','kien.daotrung@phenikaa-uni.edu.vn','+84837951681','Khoa Quản trị kinh doanh'),
('PGS.TS. Nguyễn Thị Gấm','Phó Trưởng khoa;Trưởng bộ môn Marketing','gam.nguyenthi@phenikaa-uni.edu.vn','+84948632736','Khoa Quản trị kinh doanh'),
('TS. Vũ Văn Thịnh','Phó Trưởng Khoa','thinh.vuvan@phenikaa-uni.edu.vn','+84xxxxxxxxx','Khoa Quản trị kinh doanh'),
('TS. Lê Tiến Mười','Phó Trưởng bộ môn Quản trị kinh doanh tổng hợp','muoi.letien@phenikaa-uni.edu.vn','+84953432665','Khoa Quản trị kinh doanh'),
('TS. Nguyễn Quốc Tuấn','Giảng viên','tuan.nguyenquoc@phenikaa-uni.edu.vn','+84451155950','Khoa Quản trị kinh doanh'),
('TS. Hoàng Thu Hiền','Giảng viên','hien.hoangthu@phenikaa-uni.edu.vn','+84712190041','Khoa Quản trị kinh doanh'),
('TS. Phạm Việt Thắng','Giảng viên','thang.phamviet@phenikaa-uni.edu.vn','+84553168958','Khoa Quản trị kinh doanh'),
('ThS.NCS. Cao Cẩm Linh','Giảng viên','linh.caocam@phenikaa-uni.edu.vn','+84320285285','Khoa Quản trị kinh doanh'),
('ThS.NCS. Nguyễn Thị Ngọc Anh','Giảng viên','anh.nguyenthingoc@phenikaa-uni.edu.vn','+84637353830','Khoa Quản trị kinh doanh'),
('ThS.NCS. Lê Tuấn Linh','Giảng viên','linh.letuan@phenikaa-uni.edu.vn','+84515008673','Khoa Quản trị kinh doanh'),
('ThS.NCS. Nguyễn Đức Lương','Giảng viên','luong.nguyenduc@phenikaa-uni.edu.vn','+84311081909','Khoa Quản trị kinh doanh'),
('ThS.NCS. Đinh Lê Đắc','Giảng viên','dac.dinhle@phenikaa-uni.edu.vn','+84828272515','Khoa Quản trị kinh doanh'),
('ThS.NCS. Hoàng Lệ Huyền','Giảng viên','huyen.hoangle@phenikaa-uni.edu.vn','+84892209705','Khoa Quản trị kinh doanh'),
('ThS. Nguyễn Văn Duy','Giảng viên','duy.nguyenvan1@phenikaa-uni.edu.vn','+84616645090','Khoa Quản trị kinh doanh'),
('ThS. Trương Tiến Bình','Giảng viên','binh.truongtien@phenikaa-uni.edu.vn','+84837369540','Khoa Quản trị kinh doanh'),
('ThS.NCS. Phan Thị Thuỳ','Giảng viên','thuy.phanthi@phenikaa-uni.edu.vn','+84748821555','Khoa Quản trị kinh doanh'),
('TS. Nguyễn Viết Đăng','Giảng viên','dang.nguyenviet@phenikaa-uni.edu.vn','+84441168120','Khoa Quản trị kinh doanh'),
('ThS.NCS. Nguyễn Ánh Tuyết','Giảng viên','tuyet.nguyenanh@phenikaa-uni.edu.vn','+84659479487','Khoa Quản trị kinh doanh'),
('ThS. Nguyễn Thị Thanh Huyền','Giảng viên','huyen.nguyenthithanh@phenikaa-uni.edu.vn','+84895237986','Khoa Quản trị kinh doanh'),
('ThS. Phạm Thuỳ Dương','Giảng viên','duong.phamthuy1@phenikaa-uni.edu.vn','+84663578315','Khoa Quản trị kinh doanh'),
('ThS. Đào Thị Lành','Giảng viên','lanh.daothi@phenikaa-uni.edu.vn','+84821363263','Khoa Quản trị kinh doanh'),
('ThS.NCS. Nguyễn Tiến Đạo','Giảng viên','dao.nguyentien@phenikaa-uni.edu.vn','+84753123867','Khoa Quản trị kinh doanh'),
('ThS.NCS. Nguyễn Tuấn Thành','Giảng viên','thanh.nguyentuan@phenikaa-uni.edu.vn','+84734495896','Khoa Quản trị kinh doanh'),
('TS. Nguyễn Thị Mơ','Trưởng bộ môn Quản trị nhân lực','mo.nguyenthi@phenikaa-uni.edu.vn','+84438950005','Khoa Quản trị kinh doanh'),
('PGS.TS. Nguyễn Bá Ngãi','Giảng viên','ngai.nguyenba@phenikaa-uni.edu.vn','+84340407673','Khoa Quản trị kinh doanh'),
('TS. Trương Tuấn Linh','Giảng viên','linh.truongtuan@phenikaa-uni.edu.vn','+84928392907','Khoa Quản trị kinh doanh'),
('TS. Nguyễn Thị Thuý','Giảng viên','thuy.nguyenthi2@phenikaa-uni.edu.vn','+84903005681','Khoa Quản trị kinh doanh'),
('TS. Lê Quang Thắng','Giảng viên','thang.lequang@phenikaa-uni.edu.vn','+84519237464','Khoa Quản trị kinh doanh'),
('ThS.NCS. Đinh Thị Hà','Giảng viên','ha.dinhthi@phenikaa-uni.edu.vn','+84367050096','Khoa Quản trị kinh doanh'),
('ThS.NCS. Đỗ Nhật Anh','Giảng viên','anh.donhat@phenikaa-uni.edu.vn','+84301748812','Khoa Quản trị kinh doanh'),

('TS. Ngô Vi Dũng','Trưởng khoa','dung.ngovi@phenikaa-uni.edu.vn','+84600568722','Khoa Kinh tế và Kinh doanh quốc tế'),
('TS. Trần Tuấn Việt','Phó trưởng khoa','viet.trantuan@phenikaa-uni.edu.vn','+84425572561','Khoa Kinh tế và Kinh doanh quốc tế'),
('TS. Tạ Thị Lệ Yên','Trưởng bộ môn Quản lý kinh tế','yen.tathile@phenikaa-uni.edu.vn','+84568006582','Khoa Kinh tế và Kinh doanh quốc tế'),
('TS. Nguyễn Đình Đạo','Phó trưởng bộ môn','dao.nguyendinh@phenikaa-uni.edu.vn','+84828169517','Khoa Kinh tế và Kinh doanh quốc tế'),
('PGS.TS. Ngô Văn Hiền','Giảng viên','hien.ngovan@phenikaa-uni.edu.vn','+84372670497','Khoa Kinh tế và Kinh doanh quốc tế'),
('PGS.TS. Bùi Duy Phú','Giảng viên','phu.buiduy@phenikaa-uni.edu.vn','+84442970694','Khoa Kinh tế và Kinh doanh quốc tế'),
('TS. Phạm Thị Lý','Giảng viên','ly.phamthi@phenikaa-uni.edu.vn','+84625829863','Khoa Kinh tế và Kinh doanh quốc tế'),
('ThS.NCS. Dương Thị Thanh Hương','Giảng viên','huong.duongthithanh@phenikaa-uni.edu.vn','+84615845521','Khoa Kinh tế và Kinh doanh quốc tế'),
('ThS.NCS. Vũ Thị Minh Ngọc','Giảng viên','ngoc.vuthiminh@phenikaa-uni.edu.vn','+84800207512','Khoa Kinh tế và Kinh doanh quốc tế'),
('ThS. Nguyễn Thanh Hiền','Giảng viên','hien.nguyenthanh@phenikaa-uni.edu.vn','+84998060423','Khoa Kinh tế và Kinh doanh quốc tế'),
('ThS. Lương Hoàng Phương Thảo','Giảng viên','thao.luonghoangphuong@phenikaa-uni.edu.vn','+84306953448','Khoa Kinh tế và Kinh doanh quốc tế'),
('ThS. Nguyễn Mai Hạ','Giảng viên','ha.nguyenmai@phenikaa-uni.edu.vn','+84862395261','Khoa Kinh tế và Kinh doanh quốc tế'),
('ThS.NCS Vũ Phú Trí','Giảng viên','tri.vuphu@phenikaa-uni.edu.vn','+84887038252','Khoa Kinh tế và Kinh doanh quốc tế'),
('GS. Lee Song Kun','Giảng viên','songkun.lee@phenikaa-uni.edu.vn','+84547437160','Khoa Kinh tế và Kinh doanh quốc tế'),
('ThS. Đinh Xuân Chung','Giảng viên','chung.dinhxuan@phenikaa-uni.edu.vn','+84800535424','Khoa Kinh tế và Kinh doanh quốc tế'),
('ThS. Nguyễn Thế Hải','Giảng viên','hai.nguyenthe@phenikaa-uni.edu.vn','+84358520917','Khoa Kinh tế và Kinh doanh quốc tế'),
('ThS. Phạm Hồng Linh','Giảng viên','linh.phamhong@phenikaa-uni.edu.vn','+84368071712','Khoa Kinh tế và Kinh doanh quốc tế'),
('ThS. Nguyễn Thị Thoa','Giảng viên','thoa.nguyenthi@phenikaa-uni.edu.vn','+84428666033','Khoa Kinh tế và Kinh doanh quốc tế'),
('ThS. Trần Hữu Đông','Giảng viên','dong.tranhuu@phenikaa-uni.edu.vn','+84547307046','Khoa Kinh tế và Kinh doanh quốc tế'),
('ThS. Lê Thị Minh Hồng','Giảng viên','hong.lethiminh@phenikaa-uni.edu.vn','+84641093502','Khoa Kinh tế và Kinh doanh quốc tế'),
('TS. Bùi Qúy Thuấn','Trưởng bộ môn Logistics và quản lý chuỗi cung ứng','thuan.buiquy@phenikaa-uni.edu.vn','+84875162527','Khoa Kinh tế và Kinh doanh quốc tế'),
('PGS.TS. Nguyễn Khánh Doanh','Giảng viên','doanh.nguyenkhanh@phenikaa-uni.edu.vn','+84395058327','Khoa Kinh tế và Kinh doanh quốc tế'),
('TS. Đồng Thị Vân Hồng','Giảng viên','hong.dongthivan@phenikaa-uni.edu.vn','+84929091717','Khoa Kinh tế và Kinh doanh quốc tế'),
('ThS. Đỗ Hải An','Giảng viên','an.dohai@phenikaa-uni.edu.vn','+84699559772','Khoa Kinh tế và Kinh doanh quốc tế'),
('ThS. Phạm Thái Hòa','Giảng viên','hoa.phamthai@phenikaa-uni.edu.vn','+84462950047','Khoa Kinh tế và Kinh doanh quốc tế'),

('TS. Nguyễn Thành Công','Trưởng Khoa','cong.nguyenthanh@phenikaa-uni.edu.vn','+84442453655','Khoa Tài chính - Kế toán'),
('TS. Trần Thị Ngọc Trâm','Phó Trưởng khoa','tram.tranthingoc@phenikaa-uni.edu.vn','+84544808651','Khoa Tài chính - Kế toán'),
('PGS. TS. Nguyễn Thị Lời','Trưởng Bộ môn Kế toán - Kiểm toán','loi.nguyenthi@phenikaa-uni.edu.vn','+84533024211','Khoa Tài chính - Kế toán'),
('PGS. TS. Tô Xuân Thanh','Giảng viên','thanh.toxuan@phenikaa-uni.edu.vn','+84533867052','Khoa Tài chính - Kế toán'),
('ThS. Nguyễn Văn Kỳ','Giảng viên - Phó chánh Văn phòng Trường','ky.nguyenvan@phenikaa-uni.edu.vn','+84808631463','Khoa Tài chính - Kế toán'),
('ThS. Đào Bích Ngọc','Phó Trưởng Bộ môn Tài chính ngân hàng','ngoc.daobich@phenikaa-uni.edu.vn','+84496210896','Khoa Tài chính - Kế toán'),
('ThS. Lê Tuyết Nhung','Phó Trưởng Bộ môn Kế toán','nhung.letuyet@phenikaa-uni.edu.vn','+84365213546','Khoa Tài chính - Kế toán'),
('TS. Nguyễn Thị Thuận','Giảng viên','thuan1.nguyenthi@phenikaa-uni.edu.vn','+84681349207','Khoa Tài chính - Kế toán'),
('ThS. Trần Thị Mơ','Giảng viên','mo.tranthi@phenikaa-uni.edu.vn','+84877894284','Khoa Tài chính - Kế toán'),
('ThS. Nguyễn Thị Thục Hiền','Giảng viên','hien.nguyenthithuc@phenikaa-uni.edu.vn','+84403928462','Khoa Tài chính - Kế toán'),
('ThS. Trần Thị Phương Oanh','Giảng viên','oanh.tranthiphuong@phenikaa-uni.edu.vn','+84xxxxxxxxx','Khoa Tài chính - Kế toán'),
('ThS. Đặng Thu Lan','Giảng viên','lan.dangthu@phenikaa-uni.edu.vn','+84677698474','Khoa Tài chính - Kế toán'),
('ThS. Nguyễn Thị Bích Ngọc','Giảng viên','ngoc.nguyenthibich1@phenikaa-uni.edu.vn','+84656181056','Khoa Tài chính - Kế toán'),
('ThS. Nguyễn Hoàng Lan','Giảng viên','lan.nguyenhoang@phenikaa-uni.edu.vn','+84884449778','Khoa Tài chính - Kế toán'),
('ThS. Nguyễn Tuấn Phong','Giảng viên','phong.nguyentuan@phenikaa-uni.edu.vn','+84785780314','Khoa Tài chính - Kế toán'),
('TS. Nguyễn Ngọc Minh','Giảng viên','minh.nguyenngoc@phenikaa-uni.edu.vn','+84610347350','Khoa Tài chính - Kế toán'),
('ThS. Trần Thúy Quỳnh','Giảng viên','quynh.tranthuy@phenikaa-uni.edu.vn','+84762306668','Khoa Tài chính - Kế toán'),
('ThS. Trần Thảo Nguyên','Giảng viên','nguyen.tranthao@phenikaa-uni.edu.vn','+84866045453','Khoa Tài chính - Kế toán'),
('ThS. Phạm Thị Thùy Dương','Giảng viên','duong.phamthithuy@phenikaa-uni.edu.vn','+84488883576','Khoa Tài chính - Kế toán'),
('ThS. Kiều Thị Vân Anh','Giảng viên','anh.kieuthivan@phenikaa-uni.edu.vn','+84718880611','Khoa Tài chính - Kế toán'),
('ThS. Ngô Hồng Hạnh','Giảng viên','hanh.ngohong@phenikaa-uni.edu.vn','+84840873352','Khoa Tài chính - Kế toán'),

('TS. Nguyễn Quang Vinh','Trưởng Khoa, Trưởng bộ môn Du lịch','vinh.nguyenquang@phenikaa-uni.edu.vn','+84763926756','Khoa Du lịch - Khách sạn'),
('TS. Trần Đức Thành','Phó trưởng khoa, Trưởng bộ môn Khách sạn','thanh.tranduc@phenikaa-uni.edu.vn','+84971044680','Khoa Du lịch - Khách sạn'),
('TS. Lê Ngọc Tuấn','Phó trưởng khoa','tuan.lengoc@phenikaa-uni.edu.vn','+84419337207','Khoa Du lịch - Khách sạn'),
('TS. Đỗ Khánh Chi','Trưởng Bộ môn Cơ sở Ngành','chi.dokhanh1@phenikaa-uni.edu.vn','+84322159677','Khoa Du lịch - Khách sạn'),
('NCS.ThS. Lê Đình Tiến','Phó Trưởng bộ môn Du lịch','tien.ledinh@phenikaa-uni.edu.vn','+84685467191','Khoa Du lịch - Khách sạn'),
('ThS. Trương Mai Ngọc','Giảng viên','ngoc.truongmai@phenikaa-uni.edu.vn','+84830264723','Khoa Du lịch - Khách sạn'),
('ThS. Trần Thị Nguyệt Quế','Giảng viên','que.tranthinguyet@phenikaa-uni.edu.vn','+84786070545','Khoa Du lịch - Khách sạn'),
('ThS. Đỗ Diệu Linh','Giảng viên','linh.dodieu@phenikaa-uni.edu.vn','+84856362755','Khoa Du lịch - Khách sạn'),
('ThS. Đồng Thị Hà Uyên','Giảng viên','uyen.dongthiha@phenikaa-uni.edu.vn','+84xxxxxxxxx','Khoa Du lịch - Khách sạn'),
('NCS. ThS Trần Bá Duy','Giảng viên','duy.tranba@phenikaa-uni.edu.vn','+84645651653','Khoa Du lịch - Khách sạn'),
('NCS. ThS Ngô Anh Tuấn','Giảng viên','tuan.ngoanh@phenikaa-uni.edu.vn','+84381091344','Khoa Du lịch - Khách sạn'),
('NCS. ThS Trần Thị Kim Bảo','Giảng viên','bao.tranthikim@phenikaa-uni.edu.vn','+84598816668','Khoa Du lịch - Khách sạn'),
('ThS. Nguyễn Trọng Đạt','Giảng viên','dat.nguyentrong@phenikaa-uni.edu.vn','+84529266006','Khoa Du lịch - Khách sạn'),
('ThS. Lê Quang Huy','Giảng viên','huy.lequang@phenikaa-uni.edu.vn','+84921128340','Khoa Du lịch - Khách sạn'),
('ThS. Trần Ngọc Quyết','Giảng viên','quyet.tranngoc@phenikaa-uni.edu.vn','+84598114658','Khoa Du lịch - Khách sạn'),
('ThS. Nguyễn Huyền Trang','Giảng viên','trang.nguyenhuyen1@phenikaa-uni.edu.vn','+84374225816','Khoa Du lịch - Khách sạn'),
('ThS. Phan Duy Quang','Giảng viên','quang.phanduy@phenikaa-uni.edu.vn','+84469012048','Khoa Du lịch - Khách sạn'),
('ThS. Trần Thị Mỹ Linh','Giảng viên','linh.tranthimy@phenikaa-uni.edu.vn','+84473804204','Khoa Du lịch - Khách sạn'),
('ThS. Đỗ Huyền Trang','Giảng viên','trang.dohuyen@phenikaa-uni.edu.vn','+84394698128','Khoa Du lịch - Khách sạn'),
('ThS. Vũ Trọng Hòa','Giảng viên','hoa.vutrong@phenikaa-uni.edu.vn','+84373098291','Khoa Du lịch - Khách sạn'),
('ThS. Mai Văn Trọng','Giảng viên','trong.maivan@phenikaa-uni.edu.vn','+84630685680','Khoa Du lịch - Khách sạn'),
('ThS. Lương Lê Hồng Ngọc','Giảng viên','ngoc.luonglehong@phenikaa-uni.edu.vn','+84xxxxxxxxx','Khoa Du lịch - Khách sạn'),
('ThS. Phùng Thị Thanh Hiền','Giảng viên','hien.phungthithanh@phenikaa-uni.edu.vn','+84xxxxxxxxx','Khoa Du lịch - Khách sạn'),

('TS. Đinh Thị Bảo Hương','Phó Trưởng khoa Phụ trách','huong.dinhthibao@phenikaa-uni.edu.vn','+84751465794','Khoa Ngôn ngữ Anh'),
('TS. Trần Thị Thanh Hương','Phó Trưởng Khoa kiêm nhiệm Trưởng Bộ môn Tiếng Anh chuyên ngành','huong.tranthithanh@phenikaa-uni.edu.vn','+84707740499','Khoa Ngôn ngữ Anh'),
('PGS. TS. Nguyễn Thị Thanh Hương','Trưởng Bộ môn Lý thuyết tiếng','huong.nguyenthithanh@phenikaa-uni.edu.vn','+84723366900','Khoa Ngôn ngữ Anh'),
('ThS. Hoàng Văn Hoạt','Trưởng Bộ môn Dịch','hoat.hoangvan@phenikaa-uni.edu.vn','+84424842036','Khoa Ngôn ngữ Anh'),
('ThS. Dương Hồng Quân','Giảng viên - Phó Trưởng Phụ trách Bộ môn Thực hành tiếng','quan.duonghong@phenikaa-uni.edu.vn','+84825401967','Khoa Ngôn ngữ Anh'),
('TS. Nguyễn Thị Thuỳ Linh','Giảng viên - Phó Trưởng Bộ môn Lý thuyết tiếng','linh.nguyenthithuy@phenikaa-uni.edu.vn','+84688473027','Khoa Ngôn ngữ Anh'),
('ThS. Phan Thảo Nguyên','Giảng viên - Phó Trưởng Bộ môn Tiếng Anh chuyên ngành','nguyen.phanthao@phenikaa-uni.edu.vn','+84860501386','Khoa Ngôn ngữ Anh'),
('ThS. Phạm Thị Phương Thảo','Giảng viên - Phó Trưởng Bộ môn Thực hành tiếng','thao.phamthiphuong@phenikaa-uni.edu.vn','+84672144717','Khoa Ngôn ngữ Anh'),
('ThS. Đỗ Thị Trang','Giảng viên - Phó Trưởng Bộ môn Thực hành tiếng','trang.dothi@phenikaa-uni.edu.vn','+84398625294','Khoa Ngôn ngữ Anh'),
('TS. Nguyễn Thị Bích Thuỷ','Giảng viên','thuy.nguyenthibich@phenikaa-uni.edu.vn','+84797593960','Khoa Ngôn ngữ Anh'),
('PGS. TS Nguyễn Đăng Sửu','Giảng viên','suu.nguyendang@phenikaa-uni.edu.vn','+84962774862','Khoa Ngôn ngữ Anh'),
('CN. Nguyễn Thị Phượng','Thư ký/Giáo vụ','phuong.nguyenthi@phenikaa-uni.edu.vn','+84973425921','Khoa Ngôn ngữ Anh'),
('ThS. Nguyễn Ngọc Hải','Giảng viên','hai.nguyenngoc@phenikaa-uni.edu.vn','+84691258006','Khoa Ngôn ngữ Anh'),
('ThS. Phạm Thị Thanh Hương','Giảng viên','huong.phamthithanh@phenikaa-uni.edu.vn','+84384991173','Khoa Ngôn ngữ Anh'),
('TS. Dương Thị Hồng Thái','Giảng viên','thai.duongthihong@phenikaa-uni.edu.vn','+84543307186','Khoa Ngôn ngữ Anh'),
('ThS. Vũ Anh Thư','Giảng viên','thu.vuanh@phenikaa-uni.edu.vn','+84810369052','Khoa Ngôn ngữ Anh'),
('ThS. Trần Thanh Thư','Giảng viên','thu.tranthanh@phenikaa-uni.edu.vn','+84872699255','Khoa Ngôn ngữ Anh'),
('ThS. Phan Thị Mai','Giảng viên','mai.phanthi@phenikaa-uni.edu.vn','+84723021016','Khoa Ngôn ngữ Anh'),
('ThS. Lại Thị Phương Linh','Giảng viên','linh.laithiphuong@phenikaa-uni.edu.vn','+84977138510','Khoa Ngôn ngữ Anh'),
('ThS. Phan Thuỳ Linh','Giảng viên','linh.phanthuy@phenikaa-uni.edu.vn','+84787714228','Khoa Ngôn ngữ Anh'),
('ThS. Lương Quỳnh Anh','Giảng viên','anh.luongquynh@phenikaa-uni.edu.vn','+84964630094','Khoa Ngôn ngữ Anh'),
('ThS. Nguyễn Võ Hải Triều','Giảng viên','trieu.nguyenvohai@phenikaa-uni.edu.vn','+84376518994','Khoa Ngôn ngữ Anh'),
('ThS. Trần Thuỳ Linh','Giảng viên','linh.tranthuy@phenikaa-uni.edu.vn','+84775889446','Khoa Ngôn ngữ Anh'),
('ThS. Trịnh Thị Hằng','Giảng viên','hang.trinhthi@phenikaa-uni.edu.vn','+84695221537','Khoa Ngôn ngữ Anh'),
('ThS. Nguyễn Vũ Giang','Giảng viên','giang.nguyenvu@phenikaa-uni.edu.vn','+84538699653','Khoa Ngôn ngữ Anh'),
('ThS. Nguyễn Thị Kiều Lê','Giảng viên','le.nguyenthikieu@phenikaa-uni.edu.vn','+84691414828','Khoa Ngôn ngữ Anh'),
('ThS. Đỗ Thị Hương','Giảng viên','huong.dothi1@phenikaa-uni.edu.vn','+84811437452','Khoa Ngôn ngữ Anh'),
('ThS. Bùi Thanh Nga','Giảng viên','nga.buithanh@phenikaa-uni.edu.vn','+84361529110','Khoa Ngôn ngữ Anh'),
('ThS. Nguyễn Xuân Hải','Giảng viên','hai.nguyenxuan@phenikaa-uni.edu.vn','+84846980606','Khoa Ngôn ngữ Anh'),
('ThS. Lê Thị Thanh Mai','Giảng viên','mai.lethithanh@phenikaa-uni.edu.vn','+84890469812','Khoa Ngôn ngữ Anh'),
('ThS. Đặng Minh Tâm','Giảng viên','tam.dangminh@phenikaa-uni.edu.vn','+84870186230','Khoa Ngôn ngữ Anh'),
('ThS. Vũ Quỳnh Trúc','Giảng viên','truc.vuquynh@phenikaa-uni.edu.vn','+84549356327','Khoa Ngôn ngữ Anh'),
('ThS. Nguyễn Thu Trang','Giảng viên','trang.nguyenthu1@phenikaa-uni.edu.vn','+84786019750','Khoa Ngôn ngữ Anh'),
('ThS. Phạm Việt Phú','Giảng viên','phu.phamviet@phenikaa-uni.edu.vn','+84760587524','Khoa Ngôn ngữ Anh'),

('TS. Vũ Thị Hà','Trưởng khoa','ha.vuthi@phenikaa-uni.edu.vn','+84331100153','Khoa Ngôn ngữ Trung Quốc'),
('TS. Phạm Thuý Hồng','Phó trưởng khoa','hong.phamthuy@phenikaa-uni.edu.vn','+84801652304','Khoa Ngôn ngữ Trung Quốc'),
('TS. Trần Thị Huệ','Phó trưởng khoa','hue.tranthi@phenikaa-uni.edu.vn','+84948736317','Khoa Ngôn ngữ Trung Quốc'),
('TS. Đặng Quỳnh Dung','Trưởng bộ môn Thực hành tiếng','dung.dangquynh@phenikaa-uni.edu.vn','+84410280371','Khoa Ngôn ngữ Trung Quốc'),
('ThS. Bùi Huy Hoàng','Giảng viên; Phó trưởng Bộ môn Thực hành tiếng','hoang.buihuy@phenikaa-uni.edu.vn','+84809302496','Khoa Ngôn ngữ Trung Quốc'),
('ThS. Vũ Thị Bảo Nguyệt','Giảng viên','nguyet.vuthibao@phenikaa-uni.edu.vn','+84315473882','Khoa Ngôn ngữ Trung Quốc'),
('ThS. Nguyễn Thu Thuỷ','Giảng viên','thuy.nguyenthu@phenikaa-uni.edu.vn','+84899424824','Khoa Ngôn ngữ Trung Quốc'),
('ThS. Nguyễn Thị Kiều Linh','Giảng viên','linh.nguyenthikieu@phenikaa-uni.edu.vn','+84719974029','Khoa Ngôn ngữ Trung Quốc'),
('ThS. Trần Thị Thu Thuỷ','Giảng viên','thuy.tranthithu@phenikaa-uni.edu.vn','+84828621062','Khoa Ngôn ngữ Trung Quốc'),
('ThS. Nguyễn Huyền Trâm','Giảng viên','tram.nguyenhuyen@phenikaa-uni.edu.vn','+84931050877','Khoa Ngôn ngữ Trung Quốc'),
('ThS. Đỗ Văn Trình','Giảng viên','trinh.dovan@phenikaa-uni.edu.vn','+84873789532','Khoa Ngôn ngữ Trung Quốc'),
('ThS. Nguyễn Minh Đạt','Giảng viên','dat.nguyenminh@phenikaa-uni.edu.vn','+84895187312','Khoa Ngôn ngữ Trung Quốc'),
('ThS. Nguyễn Lệ Thuỷ','Giảng viên','thuy.nguyenle@phenikaa-uni.edu.vn','+84699717793','Khoa Ngôn ngữ Trung Quốc'),
('ThS. Triệu Khánh Huyền','Giảng viên','huyen.trieukhanh@phenikaa-uni.edu.vn','+84435812598','Khoa Ngôn ngữ Trung Quốc'),
('ThS. Trần Thị Thắm','Giảng viên','tham.tranthi@phenikaa-uni.edu.vn','+84420555123','Khoa Ngôn ngữ Trung Quốc'),
('ThS. Lê Phương Thảo','Giảng viên','thao.lephuong@phenikaa-uni.edu.vn','+84518829775','Khoa Ngôn ngữ Trung Quốc'),
('ThS. Nguyễn Thị Thu Trang','Giảng viên','trang.nguyenthithu@phenikaa-uni.edu.vn','+84604816566','Khoa Ngôn ngữ Trung Quốc'),
('ThS. Nguyễn Thái Thùy Linh','Giảng viên','linh.nguyenthaithuy@phenikaa-uni.edu.vn','+84828193627','Khoa Ngôn ngữ Trung Quốc'),
('ThS. Dương Thị Hồng Nhung','Giảng viên','nhung.duongthihong@phenikaa-uni.edu.vn','+84659968606','Khoa Ngôn ngữ Trung Quốc'),
('ThS. Vũ Thùy Linh','Giảng viên','linh.vuthuy@phenikaa-uni.edu.vn','+84972127134','Khoa Ngôn ngữ Trung Quốc'),
('ThS. Triệu Thị Nụ','Giảng viên','nu.trieuthi@phenikaa-uni.edu.vn','+84487337494','Khoa Ngôn ngữ Trung Quốc'),
('ThS. Lưu Thị Phúc','Giảng viên','phuc.luuthi@phenikaa-uni.edu.vn','+84xxxxxxxxx','Khoa Ngôn ngữ Trung Quốc'),
('ThS. Nguyễn Thu Huyền','Giảng viên','huyen.nguyenthu@phenikaa-uni.edu.vn','+84xxxxxxxxx','Khoa Ngôn ngữ Trung Quốc'),
('ThS. Nguyễn Thị Phương Hồng','Giảng viên','hong.nguyenthiphuong@phenikaa-uni.edu.vn','+84xxxxxxxxx','Khoa Ngôn ngữ Trung Quốc'),

('PGS.TS Nguyễn Tô Chung','Hiệu trưởng, Phó Giáo sư, Tiến sĩ, Giảng viên Cao cấp','chung.nguyento@phenikaa-uni.edu.vn','+84320189233','Khoa Ngôn ngữ Nhật Bản'),
('TS Trương Thị Mai','Trưởng khoa','mai.truongthi@phenikaa-uni.edu.vn','+84713843455','Khoa Ngôn ngữ Nhật Bản'),
('ThS Đinh Thị Ngọc Linh','Phó trưởng khoa','linh.dinhthingoc@phenikaa-uni.edu.vn','+84502608380','Khoa Ngôn ngữ Nhật Bản'),
('PGS TS Đỗ Hoàng Ngân','Trưởng bộ môn, Phó Giáo sư, Tiến sĩ, Giảng viên cao cấp','ngan.dohoang@phenikaa-uni.edu.vn','+84831405750','Khoa Ngôn ngữ Nhật Bản'),
('TS Lê Hà Phương','Trưởng Bộ môn','phuong.leha@phenikaa-uni.edu.vn','+84611734069','Khoa Ngôn ngữ Nhật Bản'),
('ThS Lê Thị Ngọc','Trưởng bộ môn','ngoc.lethi@phenikaa-uni.edu.vn','+84725856211','Khoa Ngôn ngữ Nhật Bản'),
('ThS Thẩm Thúy Hồng','Trưởng bộ môn','hong.thamthuy@phenikaa-uni.edu.vn','+84929923027','Khoa Ngôn ngữ Nhật Bản'),
('ThS Hoàng Diệp Anh','Giảng viên','anh.hoangdiep@phenikaa-uni.edu.vn','+84756211156','Khoa Ngôn ngữ Nhật Bản'),
('ThS Trần Thị Việt Hà','Giảng viên','ha.tranthiviet@phenikaa-uni.edu.vn','+84880628956','Khoa Ngôn ngữ Nhật Bản'),
('ThS Giang Thị Thanh Nhã','Giảng viên','nha.giangthithanh@phenikaa-uni.edu.vn','+84695387963','Khoa Ngôn ngữ Nhật Bản'),
('ThS Nguyễn Thị Thu Hường','Giảng viên','huong.nguyenthithu1@phenikaa-uni.edu.vn','+84696703097','Khoa Ngôn ngữ Nhật Bản'),
('ThS Tô Thị Thanh','Giảng viên','thanh.tothi@phenikaa-uni.edu.vn','+84772142049','Khoa Ngôn ngữ Nhật Bản'),
('ThS Nguyễn Thị Minh Trang','Giảng viên','trang.nguyenthiminh1@phenikaa-uni.edu.vn','+84643484879','Khoa Ngôn ngữ Nhật Bản'),
('ThS Nguyễn Thị Bích Ngọc','Giảng viên','ngoc.nguyenthibich2@phenikaa-uni.edu.vn','+84895394801','Khoa Ngôn ngữ Nhật Bản'),
('Cử nhân Lương Văn Phong','Giáo vụ/Trợ lý Khoa','phong.luongvan@phenikaa-uni.edu.vn','+84842046035','Khoa Ngôn ngữ Nhật Bản'),

('ThS. Nguyễn Thúy Yên','Phó Trưởng khoa phụ trách','yen.nguyenthuy@phenikaa-uni.edu.vn','+84xxxxxxxxx','Khoa Ngôn ngữ Pháp'),
('TS. Đặng Kim Hoa','Phó Trưởng khoa','hoa.dangkim@phenikaa-uni.edu.vn','+84xxxxxxxxx','Khoa Ngôn ngữ Pháp'),
('ThS. Ngô Hoàng Vĩnh','Giảng viên/nhà nghiên cứu','vinh.ngohoang@phenikaa-uni.edu.vn','+84xxxxxxxxx','Khoa Ngôn ngữ Pháp'),

('TS Nguyễn Lệ Thu','Trưởng khoa','thu.nguyenle@phenikaa-uni.edu.vn','+84913273978','Khoa Ngôn ngữ Hàn Quốc'),
('ThS Vũ Thanh Hải','Phó Trưởng khoa','hai.vuthanh@phenikaa-uni.edu.vn','+84697420580','Khoa Ngôn ngữ Hàn Quốc'),
('ThS Nguyễn Thị Thanh Hoa','Trưởng bộ môn Thực hành tiếng','hoa.nguyenthithanh@phenikaa-uni.edu.vn','+84746241397','Khoa Ngôn ngữ Hàn Quốc'),
('ThS Nguyễn Thị Tươi','Phó trưởng Bộ môn Thực hành tiếng','tuoi.nguyenthi@phenikaa-uni.edu.vn','+84497819105','Khoa Ngôn ngữ Hàn Quốc'),
('ThS Nguyễn Nữ Nhật Lam','Phó Trưởng bộ môn Tiếng Hàn chuyên ngành','lam.nguyennunhat@phenikaa-uni.edu.vn','+84799219659','Khoa Ngôn ngữ Hàn Quốc'),
('TS Jeong Mi Ran','Giảng viên','miran.jeong@phenikaa-uni.edu.vn','+84542897152','Khoa Ngôn ngữ Hàn Quốc'),
('TS Park JoongHyun','Giảng viên','Joonghyun.park@phenikaa-uni.edu.vn','+84637055281','Khoa Ngôn ngữ Hàn Quốc'),
('TS Nguyễn Thị Tuyết Nhung','Giảng viên','nhung.nguyenthituyet@phenikaa-uni.edu.vn','+84952778859','Khoa Ngôn ngữ Hàn Quốc'),
('ThS Nguyễn Phương Dung','Giảng viên','dung.nguyenphuong@phenikaa-uni.edu.vn','+84450688943','Khoa Ngôn ngữ Hàn Quốc'),
('ThS Lê Thị Hương','Giảng viên','huong.lethi@phenikaa-uni.edu.vn','+84372898999','Khoa Ngôn ngữ Hàn Quốc'),
('ThS Trần Thị Ngọc','Giảng viên','ngoc.tranthi@phenikaa-uni.edu.vn','+84652023309','Khoa Ngôn ngữ Hàn Quốc'),
('ThS Hoàng Anh Hải Yến','Giảng viên','yen.hoanganhhai@phenikaa-uni.edu.vn','+84994334558','Khoa Ngôn ngữ Hàn Quốc'),
('ThS Nguyễn Khánh Linh','Giảng viên','linh.nguyenkhanh@phenikaa-uni.edu.vn','+84319377286','Khoa Ngôn ngữ Hàn Quốc'),
('ThS Nguyễn Thị Ngọc Hiếu','Giảng viên','hieu.nguyenthingoc@phenikaa-uni.edu.vn','+84724721880','Khoa Ngôn ngữ Hàn Quốc'),
('ThS Nguyễn Thị Thu','Giảng viên','Thu.nguyenthi1@phenikaa-uni.edu.vn','+84844644278','Khoa Ngôn ngữ Hàn Quốc'),
('ThS Nguyễn Kim Ngân','Giảng viên','ngan.nguyenkim@phenikaa-uni.edu.vn','+84729962560','Khoa Ngôn ngữ Hàn Quốc'),
('ThS Nguyễn Thị Tịnh','Giảng viên','tinh.nguyenthi@phenikaa-uni.edu.vn','+84755212439','Khoa Ngôn ngữ Hàn Quốc'),
('ThS Hoàng Thị Liên','Giảng viên','lien.hoangthi@phenikaa-uni.edu.vn','+84578034693','Khoa Ngôn ngữ Hàn Quốc'),
('ThS Trần Tùng Ngọc','Giảng viên','ngoc.trantung@phenikaa-uni.edu.vn','+84817629222','Khoa Ngôn ngữ Hàn Quốc'),
('ThS Vũ Hà Phương','Giảng viên','phuong.vuha@phenikaa-uni.edu.vn','+84387483133','Khoa Ngôn ngữ Hàn Quốc'),
('ThS Nguyễn Văn Việt','Giảng viên','viet.nguyenvan@phenikaa-uni.edu.vn','+84484051422','Khoa Ngôn ngữ Hàn Quốc'),
('ThS Lê Thị Phương','Giảng viên','phuong.lethi@phenikaa-uni.edu.vn','+84731994294','Khoa Ngôn ngữ Hàn Quốc'),
('ThS Nguyễn Thi Ngọc Lan','Giảng viên','lan.nguyenthingoc1@phenikaa-uni.edu.vn','+84303040587','Khoa Ngôn ngữ Hàn Quốc'),
('ThS Bạch Thị Hoài Phương','Giảng viên','phuong.bachthihoai@phenikaa-uni.edu.vn','+84368893379','Khoa Ngôn ngữ Hàn Quốc'),

('GS.TS. Nguyễn Văn Khang','Trưởng Khoa','khang.nguyenvan@phenikaa-uni.edu.vn','+84912118665','Khoa Đông phương học'),
('ThS. Ngô Thị Phương Thảo','Phó Trưởng Khoa','thao.ngothiphuong@phenikaa-uni.edu.vn','+84912227355','Khoa Đông phương học'),
('TS. Trần Văn Nam','Phó Trưởng Khoa','nam.tranvan@phenikaa-uni.edu.vn','+84982839678','Khoa Đông phương học'),
('ThS. Lê Thị Hương Lan','Giảng viên','lan.lethihuong@phenikaa-uni.edu.vn','+84989039892','Khoa Đông phương học'),
('ThS. Lê Quang Minh','Giảng viên','minh.lequang@phenikaa-uni.edu.vn','+84947075066','Khoa Đông phương học'),
('ThS. Quách Hồng Hồng','Giảng viên','hong.quachhong@phenikaa-uni.edu.vn','+84941948383','Khoa Đông phương học'),
('ThS. Trịnh Như Quỳnh','Giảng viên','quynh.trinhnhu@phenikaa-uni.edu.vn','+84344146192','Khoa Đông phương học'),
('TS. Shin Seung Bok','Giảng viên','shinsbvn@gmail.com','+84839306224','Khoa Đông phương học'),
('ThS. Nguyễn Hà Chi','Giảng viên','chi.nguyenha@phenikaa-uni.edu.vn','+84387300561','Khoa Đông phương học'),
('ThS. Bùi Thị Hậu','Giảng viên','hau.buithi@phenikaa-uni.edu.vn','+84901729528','Khoa Đông phương học'),
('ThS. Nguyễn Thị Thu Trang','Giảng viên','trang.nguyenthithu2@phenikaa-uni.edu.vn','+84918601833','Khoa Đông phương học'),
('ThS. Bùi Thị Thuỳ Chi','Giảng viên','chi.buithithuy@phenikaa-uni.edu.vn','+84357209111','Khoa Đông phương học'),
('ThS. Doãn Thị Bích Diệp','Giảng viên','diep.doanthibich@phenikaa-uni.edu.vn','+84969450882','Khoa Đông phương học'),
('ThS. Nguyễn Thị Lừng','Giảng viên','lung.nguyenthi@phenikaa-uni.edu.vn','+84966246213','Khoa Đông phương học'),
('ThS. Nguyễn Thị Phương Anh','Giảng viên','anh.nguyenthiphuong1@phenikaa-uni.edu.vn','+84986693820','Khoa Đông phương học'),
('ThS. Nguyễn Văn Thụ','Giảng viên','thu.nguyenvan@phenikaa-uni.edu.vn','+84348450707','Khoa Đông phương học'),
('ThS. Phạm Thị Hồng Phượng','Giảng viên','phuong.phamthihong@phenikaa-uni.edu.vn','+84971191799','Khoa Đông phương học'),
('ThS. Nguyễn Thị Thắng','Giảng viên','thang.nguyenthi@phenikaa-uni.edu.vn','+84984629522','Khoa Đông phương học'),

('TTND. NGƯT GS. TS. BS. Đỗ Quyết','Hiệu Trưởng Trường Y Dược - Đại Học Phenikaa; Phó Tổng giám đốc Bệnh viện Đại Học Phenikaa; Trưởng khoa Y','quyet.do@phenikaa-uni.edu.vn','+84625627776','Khoa Y'),
('PGS.TS.BS. Nguyễn Thanh Hồi','Phó Hiệu Trưởng Trường Y Dược - Đại Học Phenikaa; Tổng giám đốc Bệnh viện Đại học Phenikaa; Phó Trưởng Khoa Y','hoi.nguyenthanh@phenikaa-uni.edu.vn','+84361653495','Khoa Y'),
('TS.BS. Vũ Tiến Thăng','Phó Trưởng Khoa Y; Giám đốc Trung tâm mô phỏng Đại học Phenikaa','thang.vutien@phenikaa-uni.edu.vn','+84939911592','Khoa Y'),
('TS. BS. Nguyễn Thị Sim','Phó Hiệu Trưởng Trường Y Dược - Đại Học Phenikaa; Phó Trưởng Khoa Y; Phó Tổng giám đốc Bệnh viện Đại học Phenikaa','sim.nguyenthi@phenikaa-uni.edu.vn','+84928269896','Khoa Y'),
('PGS.TS.BS. Trương Thanh Hương','Trưởng Bộ môn Nội','huong.truongthanh@phenikaa-uni.edu.vn','+84853266432','Khoa Y'),
('GS.TS.BS. TTND. Hà Văn Quyết','Trưởng Bộ môn Ngoại - Gây mê hồi sức','quyet.havan@phenikaa-uni.edu.vn','+84358877127','Khoa Y'),
('GS.TS.BS. Vương Tiến Hòa','Trưởng Bộ môn Phụ Sản','hoa.vuongtien@phenikaa-uni.edu.vn','+84430545397','Khoa Y'),
('PGS.TS.BS. Nguyễn Văn Bàng','Giảng viên Bộ môn Nhi','bang.nguyenvan@phenikaa-uni.edu.vn','+84913954638','Khoa Y'),
('TS. BS. Trần Quốc Hùng','Trưởng Bộ môn Ung Bướu','hung.tranquoc@phenikaa-uni.edu.vn','+84772158959','Khoa Y'),
('PGS.TS.BS. Trần Thị Kiệm','Giảng viên Bộ môn Ngoại - Gây mê hồi sức','kiem.tranthi@phenikaa-uni.vn','+84497310790','Khoa Y'),
('PGS.TS.BS. Nguyễn Thị Bạch Tuyết','Giảng viên Bộ môn Nội','tuyet.nguyenthibach@phenikaa-uni.edu.vn','+84907383257','Khoa Y'),
('TS.BS. Nguyễn Công Tuấn','Giảng viên Bộ môn Sản phụ Khoa','tuan.nguyencong@phenikaa-uni.edu.vn','+84537680056','Khoa Y'),
('ThS.Bác sĩ nội trú. Nguyễn Thị Thu Huyền','Giảng viên Bộ môn Nội-Y học Gia đình','huyen.nguyenthithu@phenikaa-uni.edu.vn','+84462008009','Khoa Y'),
('ThS.Bác sĩ nội trú. Tạ Thị Thịnh','Giảng viên Bộ môn Nội - Thần kinh','thinh.tathi@phenikaa-uni.edu.vn','+84399060857','Khoa Y'),
('ThS.BS. Nguyễn Bá Sơn','Giảng viên Bộ môn Ngoại - Gây mê hồi sức; Phó Trưởng Khoa Ngoại tổng hợp - Bệnh viện Đại học Phenikaa','son.nguyenba@phenikaa-uni.edu.vn','+84999692464','Khoa Y'),
('ThS.BS. Vũ Công Thắng','Giảng viên Bộ môn Ngoại - Gây mê hồi sức','thang.vucong@phenikaa-uni.edu.vn','+84505477904','Khoa Y'),
('ThS.Bác sĩ nội trú. Mai Thị Hiền Uyên','Giảng viên Bộ môn Nhi','uyen.maithihien@phenikaa-uni.edu.vn','+84792053738','Khoa Y'),
('ThS.Bác sĩ nội trú. Phùng Anh Tuấn','Giảng viên Bộ môn Ngoại - Gây mê hồi sức','tuan.phunganh@phenikaa-uni.edu.vn','+84982761262','Khoa Y'),
('ThS.Bác sĩ nội trú. Trần Thị Liên','Giảng viên Bộ môn Nội-Y học gia đình','lien.tranthi@phenikaa-uni.edu.vn','+84644503858','Khoa Y'),
('ThS.Bác sĩ nội trú. Vũ Đức Duy','Giảng viên Bộ môn Ngoại - Gây mê hồi sức','duy.vuduc@phenikaa-uni.edu.vn','+84303991830','Khoa Y'),
('ThS.Bác sĩ nội trú Nguyễn Việt Tuấn','Giảng viên Bộ môn Ngoại - Gây mê hồi sức','nguyenviettuan711@gmail.com','+84940153432','Khoa Y'),
('ThS. Bác sĩ nội trú. Trần Thi Hiền','Giảng viên Bộ môn Nội','tranhien13596@gmail.com','+84698440778','Khoa Y'),
('ThS. Bác sĩ nội trú. Nông Thảo Vy','Giảng viên Bộ môn Nội','vy.nongthao@phenikaa-uni.edu.vn','+84329997725','Khoa Y'),
('ThS. Bác sĩ nội trú. Phạm Văn Huy','Giảng viên Bộ môn Nội','phamhuy811@gmail.com','+84817462228','Khoa Y'),
('ThS. Bác sĩ nội trú. Nguyễn Duy Hiệp','Giảng viên Bộ môn Nội','hiep.nguyenduy@phenikaa-uni.edu.vn','+84333008029','Khoa Y'),
('ThS. BS. Phạm Văn Hưng','Giảng viên phụ trách Bộ môn Nhi','phamhungyhp@gmail.com','+84785572553','Khoa Y'),
('ThS. Bác sĩ nội trú. Đặng Thị Ngọc Lan','Giảng viên Bộ môn Nhi','lan.dangthingoc@phenikaa-uni.edu.vn','+84547374826','Khoa Y'),

('TS Nguyễn Duy Tuân','Trưởng khoa; Giảng viên','tuan.nguyenduy@phenikaa-uni.edu.vn','+84488129888','Khoa Y học cổ truyền'),
('TS Hoàng Thuý Hồng','Phó trưởng khoa; Giảng viên','hong.hoangthuy@phenikaa-uni.edu.vn','+84541581662','Khoa Y học cổ truyền'),
('TS Nguyễn Trường Nam','Phó trưởng khoa; Giảng viên','nam.nguyentruong@phenikaa-uni.edu.vn','+84515421991','Khoa Y học cổ truyền'),
('TS Nguyễn Văn Nhường','Giảng viên','nhuong.nguyenvan@phenikaa-uni.edu.vn','+84617893074','Khoa Y học cổ truyền'),
('TS Trần Anh Tuấn','Giảng viên','tuan.trananh1@phenikaa-uni.edu.vn','+84833301346','Khoa Y học cổ truyền'),
('TS Lưu Việt Cường','Giảng viên','cuong.luuviet@phenikaa-uni.edu.vn','+84601198460','Khoa Y học cổ truyền'),
('TS Nguyễn Minh Ngọc','Giảng viên','ngoc.nguyenminh1@phenikaa-uni.edu.vn','+84746713969','Khoa Y học cổ truyền'),
('ThS. BSNT Đỗ Ba Kế','Giảng viên','ke.doba@phenikaa-uni.edu.vn','+84652744413','Khoa Y học cổ truyền'),
('ThS. BSNT Nguyễn Thị Thuý','Giảng viên','thuy.nguyenthi@phenikaa-uni.edu.vn','+84903005681','Khoa Y học cổ truyền'),
('ThS. BSNT Dương Thế Ngọc','Giảng viên','ngoc.duongthe@phenikaa-uni.edu.vn','+84586797620','Khoa Y học cổ truyền'),
('ThS. BSNT Phạm Thu Trang','Giảng viên','trang.phamthu@phenikaa-uni.edu.vn','+84395281543','Khoa Y học cổ truyền'),
('ThS. BS Lê Thùy Chi','Giảng viên','chi.lethuy@phenikaa-uni.edu.vn','+84629585725','Khoa Y học cổ truyền'),
('ThS. BSNT Nguyễn Thị Hường','Giảng viên','huongs.nguyenthi@phenikaa-uni.edu.vn','+84993303990','Khoa Y học cổ truyền'),
('ThS. BSNT Lê Tiến Đạt','Giảng viên','dat.letien@phenikaa-uni.edu.vn','+84457256031','Khoa Y học cổ truyền'),
('ThS. BSNT Vũ Minh Phụng','Giảng viên','phung.vuminh@phenikaa-uni.edu.vn','+84637066676','Khoa Y học cổ truyền'),
('ThS. BS Trịnh Thị Hương Giang','Giảng viên','Giang.Trinhthihuong@phenikaa-uni.edu.vn','+84836910565','Khoa Y học cổ truyền'),
('ThS. BS Chử Lương Huân','Giảng viên','huan.chuluong@phenikaa-uni.edu.vn','+84744793301','Khoa Y học cổ truyền'),
('ThS. BS Ngô Hiền Linh','Giảng viên','linh.ngohien@phenikaa-uni.edu.vn','+84530019543','Khoa Y học cổ truyền'),
('ThS. BS Trần Thị Thảo','Giảng viên','thao.tranthi@phenikaa-uni.edu.vn','+84822138763','Khoa Y học cổ truyền'),

('TS. Hoàng Thị Xuân Hương','Phó Trưởng Khoa phụ trách','huong.hoangthixuan@phenikaa-uni.edu.vn','+84982501850','Khoa Điều dưỡng'),
('Tiến sỹ Phạm Thị Thu Hương','Phó Trưởng Khoa','huong.phamthithu@phenikaa-uni.edu.vn','+84935151466','Khoa Điều dưỡng'),
('PGS.TS. Trần Văn Tập','Trưởng bộ môn; Giảng viên','tranvantapbv103@gmail.com','+84972712573','Khoa Điều dưỡng'),
('PGS.TS. Hồ Sỹ Hà','Trưởng bộ môn; Giảng viên','hosyha.df@gmail.com','+84904117227','Khoa Điều dưỡng'),
('Ts.Bs. Nguyễn Cự Đồng','Giảng viên','dong.nguyencu@phenikaa-uni.edu.vn','+84626114876','Khoa Điều dưỡng'),
('Ts.Bs. Vũ Minh Thục','Giảng viên','thuc.vuminh@phenikaa-uni.edu.vn','+84966953208','Khoa Điều dưỡng'),
('Tiến sỹ Nguyễn Bá Tâm','Phó Trưởng bộ môn YTCC','tam.nguyenba@phenikaa-uni.edu.vn','+84912154555','Khoa Điều dưỡng'),
('Tiến sỹ Ngô Thị Thủy','Phó Trưởng bộ môn ĐDCB','thuy.ngothi@phenikaa-uni.edu.vn','+84902700850','Khoa Điều dưỡng'),
('BSCK1 Bùi Trọng Thái','Giảng viên','thai.buitrong@phenikaa-uni.edu.vn','+84966953208','Khoa Điều dưỡng'),
('Thạc sỹ Trần Thị Phúc Hải','Giảng viên chính','hai.tranthiphuc@phenikaa-uni.edu.vn','+84913503918','Khoa Điều dưỡng'),
('Thạc sỹ Dương Thị Nhân','Giảng viên','nhan.duongthimy@phenikaa-uni.edu.vn','+84917344606','Khoa Điều dưỡng'),
('BSCK1 Dương Thị Thu','Giảng viên','thu.duongthi@phenikaa-uni.edu.vn','+84912041299','Khoa Điều dưỡng'),
('BSCK1 Phạm Thị Chỉ','Giảng viên','chi.phamthi@phenikaa-uni.edu.vn','+84983635722','Khoa Điều dưỡng'),
('BSCK1 Trần Thị Yến','Giảng viên','yen.tranth@phenikaa-uni.edu.vn','+84912907414','Khoa Điều dưỡng'),
('Thạc sỹ Phạm Thiều Hoa','Giảng viên','phamthieuhoa301@gmail.com','+84913049606','Khoa Điều dưỡng'),
('Thạc sỹ Phạm Thị Vân','Giảng viên','van.phamthi@phenikaa-uni.edu.vn','+84916965522','Khoa Điều dưỡng'),
('Thạc sỹ Nguyễn Hồng Trang','Giảng viên','trang.nguyenhong@phenikaa-uni.edu.vn','+84989555234','Khoa Điều dưỡng'),
('Thạc sỹ Nguyễn Văn Liệp','Phó Trưởng bộ môn lâm sàng hệ ngoại','liep.nguyenvan@phenikaa-uni.edu.vn','+84912333060','Khoa Điều dưỡng'),
('Thạc sỹ Nguyễn Tất Thành','Giảng viên','thanh.nguyentat@phenikaa-uni.edu.vn','+84989274625','Khoa Điều dưỡng'),
('Thạc sỹ Phạm Thị Thùy Dung','Giảng viên','dung.phamthithuy@phenikaa-uni.edu.vn','+84983886002','Khoa Điều dưỡng'),
('Thạc sỹ Vũ Minh Thúy','Giảng viên','thuy.vuminh@phenikaa-uni.edu.vn','+84986720620','Khoa Điều dưỡng'),
('Thạc sỹ Bùi Thị Châm','Giảng viên','cham.buithi@phenikaa-uni.edu.vn','+84967384266','Khoa Điều dưỡng'),
('Thạc sỹ Nguyễn Thị Quỳnh Trang','Giảng viên','trang.nguyenthiquynh@phenikaa-uni.edu.vn','+84986720620','Khoa Điều dưỡng'),
('Thạc sỹ Nguyễn Đức Việt','Giảng viên','viet.nguyenduc@phenikaa-uni.edu.vn','+84976012049','Khoa Điều dưỡng'),
('Thạc sỹ Nguyễn Thị Thảo','Giảng viên','Thao.nguyenthi@phenikaa-uni.edu.vn','+84964316097','Khoa Điều dưỡng'),
('Kỹ sư Lê Thị Đào','Thư ký - Giáo vụ khoa','dao.lethi@phenikaa-uni.edu.vn','+84969768321','Khoa Điều dưỡng'),

('PGS.TS.BS. Trần Thị Minh Tâm','Trưởng khoa Y tế công cộng;Phó Hiệu Trưởng Trường Y Dược - Đại Học Phenikaa; Phó Trưởng Khoa Y','tam.tranthiminh@phenikaa-uni.edu.vn','+84472845100','Khoa Y tế công cộng'),
('PGS.TS.BS. Phạm Văn Thao','Giảng viên','thaok10hvqy@gmail.com','+84428875189','Khoa Y tế công cộng'),
('TS. Ngô Thị Thu Hiền','Phó Trưởng Bộ môn','hien.ngothithu@phenikaa-uni.edu.vn','+84918041150','Khoa Y tế công cộng'),
('TS.BS. Đoàn Thị Mai','Giảng viên','mai.doanthi@phenikaa-uni.edu.vn','+84446424396','Khoa Y tế công cộng'),
('ThS. Hoàng Thị Ngọc Anh','Giảng viên','anh.hoangthinh@phenikaa-uni.edu.vn','+84573412800','Khoa Y tế công cộng'),
('CN. Đinh Thị Thu Trang','Thư ký/Giáo vụ','trang.dinhthithu@phenikaa-uni.edu.vn','+84517311707','Khoa Y tế công cộng'),

('PGS.TS. Lê Văn Sơn','Trưởng khoa; Giảng viên','son.levan@phenikaa-uni.edu.vn','+84913559948','Khoa Răng Hàm Mặt'),
('TS Nguyễn Giáo Hoàng','Phó trưởng khoa; Giảng viên','hoang.nguyengiao@phenikaa-uni.edu.vn','+84966561331','Khoa Răng Hàm Mặt'),
('TS Nguyễn Thị Khánh Ly','Giảng viên','ly.nguyenthikhanh@phenikaa-uni.edu.vn','+84915159399','Khoa Răng Hàm Mặt'),
('BSCKII Nguyễn Thúy Nga','Giảng viên','nga.nguyenthuy@phenikaa-uni.edu.vn','+84904162665','Khoa Răng Hàm Mặt'),
('BSCKI Nguyễn Quốc Ái','Giảng viên','ai.nguyenquoc@phenikaa-uni.edu.vn','+84902191636','Khoa Răng Hàm Mặt'),
('BSCKI Nguyễn Thùy Linh','Giảng viên','linh.nguyenthuy@phenikaa-uni.edu.vn','+84971109366','Khoa Răng Hàm Mặt'),
('ThS Trần Thị Diệu Linh','Giảng viên','linh.tranthidieu@phenikaa-uni.edu.vn','+84971433043','Khoa Răng Hàm Mặt'),
('BSNT Nguyễn Thị Thu Hương','Giảng viên','huong.nguyenthithu2@phenikaa-uni.edu.vn','+84979455594','Khoa Răng Hàm Mặt'),
('ThS Lê Anh Tùng','Giảng viên','tung.leanh@phenikaa-uni.edu.vn','+84903265994','Khoa Răng Hàm Mặt'),
('ThS. BSCK I Nguyễn Việt Hưng','Giảng viên','hung.nguyenviet1@phenikaa-uni.edu.vn','+84342069966','Khoa Răng Hàm Mặt'),
('ThS Dương Minh Hải','Giảng viên','hai.duongminh@phenikaa-uni.edu.vn','+84342069966','Khoa Răng Hàm Mặt'),
('CN Phan Ngọc Hân','Thư kí/giáo vụ','han.phanngoc@phenikaa-uni.edu.vn','+84866017953','Khoa Răng Hàm Mặt'),
('ThS. BSNT Nguyễn Việt Anh','Giảng viên','anh.nguyenviet1@phenikaa-uni.edu.vn','+84447359944','Khoa Răng Hàm Mặt'),
('ThS. Bùi Danh Lưu','Giảng viên','luu.buidanh@phenikaa-uni.edu.vn','+84570684049','Khoa Răng Hàm Mặt'),
('TS. Nguyễn Thị Trang','Giảng viên','trang.nguyenthi@phenikaa-uni.edu.vn','+84497303893','Khoa Răng Hàm Mặt'),
('ThS.BSNT Bùi Tiến Đạt','Giảng viên','dat.buitien@phenikaa-uni.edu.vn','+84811975861','Khoa Răng Hàm Mặt'),
('BSNT. Nguyễn Thanh Nga','Giảng viên','nga.nguyenthanh@phenikaa-uni.edu.vn','+84450227879','Khoa Răng Hàm Mặt'),
('Cử nhân Lưu Thị Hằng','Điều dưỡng','hang.luuthi@phenikaa-uni.edu.vn','+84615429258','Khoa Răng Hàm Mặt'),

('PGS.TS. Nguyễn Văn Hùng','Trưởng khoa Dược','hung.nguyenvan2@phenikaa-uni.edu.vn','+84994217233','Khoa Dược'),
('PGS.TS. Dương Thị Ly Hương','Phó trưởng khoa','huong.duongthily@phenikaa-uni.edu.vn','+84334918337','Khoa Dược'),
('PGS.TS Nguyễn Quỳnh Hoa','Phó Trưởng khoa; Trưởng khoa Dược, Bệnh viện Đại học Phenikaa','hoa.nguyenquynh@phenikaa-uni.edu.vn','+84394554827','Khoa Dược'),
('TS.DS Trần Tuấn Hiệp','Phó trưởng khoa,Trưởng Bộ môn Bào chế - Sản xuất thuốc','hiep.trantuan@phenikaa-uni.edu.vn','+84816380609','Khoa Dược'),
('TS.DS. Phạm Nữ Hạnh Vân','Phó Trưởng khoa','van.phamnuhanh@phenikaa-uni.edu.vn','+84619794165','Khoa Dược'),
('TS.DS. Đặng Thị Hiền','Giảng viên','hien.dangthi@phenikaa-uni.edu.vn','+84995150767','Khoa Dược'),
('ThS.DS. Hà Thị Nhàn','Giảng viên','nhan.hathi@phenikaa-uni.edu.vn','+84821493059','Khoa Dược'),
('ThS.DS. Nguyễn Thị Hồng Giang','Giảng viên','Giang.Nguyenthihong@phenikaa-uni.edu.vn','+84347215760','Khoa Dược'),
('TS.DS. Phạm Hà Thanh Tùng','Trưởng Bộ môn Dược liệu - Dược học cổ truyền','tung.phamhathanh@phenikaa-uni.edu.vn','+84379894189','Khoa Dược'),
('PGS.TS. Nguyễn Văn Hân','Giảng viên','han.nguyenvan@phenikaa-uni.edu.vn','+84649417201','Khoa Dược'),
('TS.DS. Nguyễn Ngọc Hiếu','Giảng viên','hieu.nguyenngoc@phenikaa-uni.edu.vn','+84694426012','Khoa Dược'),
('ThS.DS. Lê Xuân Huê','Giảng viên','hue.lexuan@phenikaa-uni.edu.vn','+84847799351','Khoa Dược'),
('ThS.DS. Lê Thị Nhiên','Giảng viên','nhien.lethi@phenikaa-uni.edu.vn','+84625207687','Khoa Dược'),
('TS.DS. Phạm Giang Nam','Giảng viên','nam.phamgiang@phenikaa-uni.edu.vn','+84607468381','Khoa Dược'),
('TS.DS. Phạm Minh Hưng','Phó trưởng bộ môn Dược lý - Dược lâm sàng','hung.phamminh@phenikaa-uni.edu.vn','+84903140236','Khoa Dược'),
('TS.DS. Ngô Thị Liên','Giảng viên','Lien.Ngothi@phenikaa-uni.edu.vn','+84687741926','Khoa Dược'),
('TS.DS. Trần Thị Quyên','Giảng viên','quyen.tranthi@phenikaa-uni.edu.vn','+84357113277','Khoa Dược'),
('ThS.DS. Phùng Minh Phượng','Giảng viên','phuong.phungminh@phenikaa-uni.edu.vn','+84889881069','Khoa Dược'),
('ThS. Lương Thúy Lan','Giảng viên','Lan.Luongthuy@phenikaa-uni.edu.vn','+84690387479','Khoa Dược'),
('PGS.TS. Nguyễn Hữu Tùng','Trưởng bộ môn Hóa dược - Hóa phân tích - Kiểm nghiệm ;Trưởng nhóm nghiên cứu mạnh','tung.nguyenhuu@phenikaa-uni.edu.vn','+84477276123','Khoa Dược'),
('TS.DS. Phùng Thị Vinh','Phó trưởng bộ môn Hóa dược - Hóa phân tích - Kiểm nghiệm','vinh.phungthi@phenikaa-uni.edu.vn','+84121615477','Khoa Dược'),
('TS.DS. Hoàng Văn Hải','Giảng viên','Hai.Hoangvan@phenikaa-uni.edu.vn','+84579855829','Khoa Dược'),
('TS. Vũ Văn Tuấn','Giảng viên','Tuan.Vuvan@phenikaa-uni.edu.vn','+84360870655','Khoa Dược'),
('ThS.DS. Nguyễn Văn Giảng','Giảng viên','giang.nguyenvan@phenikaa-uni.edu.vn','+84408748330','Khoa Dược'),
('TS.DS. Trương Thanh Tùng','Trưởng Bộ môn KHCB-CS Dược','tung.truongthanh@phenikaa-uni.edu.vn','+84836285361','Khoa Dược'),
('PGS.TSKH.DS. Lê Thành Phước','Giảng viên bộ môn KHCB - Cơ sở Dược','Phuoc.lethanh@phenikaa-uni.edu.vn','+84846061052','Khoa Dược'),
('TS.DSCK2.TTƯT. Bùi Quốc Tuấn','Giảng viên','tuan.buiquoc@phenikaa-uni.edu.vn','+84419695267','Khoa Dược'),
('TS.DS. Nguyễn Minh Đức','Giảng viên','duc.nguyenminh@phenikaa-uni.edu.vn','+84672806096','Khoa Dược'),
('TS.DS. Lương Xuân Huy','Giảng viên, Nghiên cứu viên','huy.luongxuan@phenikaa-uni.edu.vn','+84571601744','Khoa Dược'),
('ThS. Bùi Thị Phương Hải','Giảng viên','hai.buithiphuong@phenikaa-uni.edu.vn','+84701670462','Khoa Dược'),
('ThS. Nguyễn Minh Tú','Giảng viên','tu.nguyenminh@phenikaa-uni.edu.vn','+84619954991','Khoa Dược'),
('ThS. DS. Dương Ngọc Thành','Kỹ Thuật viên','thanh.duongngoc@Phenikaa-uni.edu.vn','+84746455201','Khoa Dược'),
('ThS.DS. Đoàn Anh Dũng','Phó trưởng bộ môn Quản lý - Kinh tế dược','Dung.DoanAnh@phenikaa-uni.edu.vn','+84661389307','Khoa Dược'),
('TS.DS. Trần Đức Long','Giảng viên','long.tranduc@phenikaa-uni.edu.vn','+84604089269','Khoa Dược'),
('PGS.TS. Nguyễn Huy Oánh','Giảng viên','Oanh.Nguyenhuy@phenikaa-uni.edu.vn','+84695443153','Khoa Dược'),
('TS. Nguyễn Xuân Nguyên','Giảng viên','Nguyen.Nguyenxuan@phenikaa-uni.edu.vn','+84870483221','Khoa Dược'),
('DSCK1. Ngô Vĩnh Linh','Giảng viên','Linh.NgoVinh@phenikaa-uni.edu.vn','+84970573166','Khoa Dược'),
('ThS.DS. Nguyễn Thanh Thảo','Giảng viên','thao.nguyenthanh@phenikaa-uni.edu.vn','+84678221588','Khoa Dược'),

('GS.TS.BS.Nhà giáo ưu tú Cao Minh Châu','Trưởng Khoa Kỹ Thuật Y học','chau.caominh@phenikaa-uni.edu.vn','+84913343461','Khoa Kỹ thuật Y học'),
('PGS.TS.BS. Thầy thuốc Nhân dân Bùi Thị Mai An','Phó Trưởng Khoa Kỹ thuật Y học; Giảng viên chính Bộ môn Huyết học - Truyền máu','an.buithimai@phenikaa-uni.edu.vn','+84915182859','Khoa Kỹ thuật Y học'),
('GS.TS.BS. Nhà giáo Nhân dân Lưu Ngọc Hoạt','Phó Hiệu trưởng, Trưởng Khoa Y; Giám đốc Dự án Bệnh viện','hoat.luungoc@phenikaa-uni.edu.vn','+84969365140','Khoa Kỹ thuật Y học'),
('TS.BSCKII. Thầy thuốc Ưu tú Đặng Xuân Tin','Trợ lý Tổng Giám đốc; Trưởng Bộ môn Y Sinh','tin.dangxuan@phenikaa-uni.edu.vn','+84501751258','Khoa Kỹ thuật Y học'),
('PGS.TS.BS. Thầy thuốc Ưu tú Nguyễn Trọng Thông','Trưởng Bộ môn Dược lý lâm sàng, Khoa Dược','thong.nguyentrong@phenikaa-uni.edu.vn','+84314939160','Khoa Kỹ thuật Y học'),
('TS. Nguyễn Văn Tuấn','Giảng viên Bộ môn Vi sinh - Ký sinh trùng','tuan.nguyenvan@phenikaa-uni.edu.vn','+84332222722','Khoa Kỹ thuật Y học'),
('BSCKII. Nguyễn Hoàng Điệp','Giảng viên Bộ môn Vật lý trị liệu - Phục hồi chức năng','diep.nguyenhoang@phenikaa-uni.edu.vn','+84866543210','Khoa Kỹ thuật Y học'),
('TS. Trần Khánh Hoàn','Giảng viên Khoa Kỹ thuật Y học','hoan.trankhanh@phenikaa-uni.edu.vn','+84327467595','Khoa Kỹ thuật Y học'),
('ThS. BSCKII Vũ Thị Hương','Giảng viên','huong.vuthi@phenikaa-uni.edu.vn','+84912569765','Khoa Kỹ thuật Y học'),
('TS Trần Văn Biên','Trưởng bộ môn','bien.tranvan@phenikaa-uni.edu.vn','+84979428922','Khoa Kỹ thuật Y học'),
('BSCKI. Trần Thị Xuân','Giảng viên Bộ môn Y học cơ sở, Khoa Điều dưỡng','xuan.tranthi@phenikaa-uni.edu.vn','+84328062777','Khoa Kỹ thuật Y học'),
('BSCKI. Trần Thị Loan','Giảng viên Bộ môn Y học cơ sở, Khoa Điều dưỡng','loan.tranthi@phenikaa-uni.edu.vn','+84799846924','Khoa Kỹ thuật Y học'),
('ThS.Bác sĩ nội trú Nguyễn Mỹ Linh','Giảng viên Bộ môn Vi sinh Y học, Khoa Y','linh.nguyenmy@phenikaa-uni.edu.vn','+84858550997','Khoa Kỹ thuật Y học'),
('ThS.Bác sĩ nội trú Phùng Quốc Toản','Giảng viên Bộ môn Nội, Khoa Y','toan.phungquoc@phenikaa-uni.edu.vn','+84869665283','Khoa Kỹ thuật Y học'),
('ThS.BS. Nguyễn Thị Chuyên','Giảng viên Bộ môn Mô phôi Khoa Y','chuyen.nguyenthi@phenikaa-uni.edu.vn','+84833844474','Khoa Kỹ thuật Y học'),
('ThS.Bác sĩ nội trú Hoàng Duy Thái','Giảng viên Bộ môn Nội, Khoa Y','thai.hoangduy@phenikaa-uni.edu.vn','+84813298929','Khoa Kỹ thuật Y học'),
('ThS Hoàng Văn Tuân','Giảng viên','tuan.hoangvan1@phenikaa-uni.edu.vn','+84982161847','Khoa Kỹ thuật Y học'),
('ThS Nguyễn Tổng Thống','Giảng viên','thong.nguyentong@phenikaa-uni.edu.vn','+84965866648','Khoa Kỹ thuật Y học'),
('ThS Đoàn Ngân Hoa','Giảng viên','hoa.doanngan@phenikaa-uni.edu.vn','+84904581095','Khoa Kỹ thuật Y học'),
('ThS Hà Thuý ngân','Giảng viên','ngan.hathuy@phenikaa-uni.edu.vn','+84987416623','Khoa Kỹ thuật Y học'),
('ThS Thân Văn Viêt','Giảng viên','viet.thanvan@phenikaa-uni.edu.vn','+84972816788','Khoa Kỹ thuật Y học'),
('Ths Phạm Hữu Thiên','Giảng viên','thien.phamhuu@phenikaa-uni.edu.vn','+84328233109','Khoa Kỹ thuật Y học'),
('Ths Nguyễn Tuấn Anh','Giảng viên','anh.nguyentuan4@phenikaa-uni.edu.vn','+84365695365','Khoa Kỹ thuật Y học'),
('Ths Phạm Minh Khánh','Giảng viên','khanh.phamminh@phenikaa-uni.edu.vn','+84939584686','Khoa Kỹ thuật Y học'),
('ThS Nguyễn Thị Việt Hà','Giảng viên','Ha.nguyenthiviet@phenikaa-uni.edu.vn','+84972847574','Khoa Kỹ thuật Y học'),
('BS Khúc Thị Hồng Hạnh','Nghiên cứu viên, Trợ giảng','hanh.khucthihong@phenikaa-uni.edu.vn','+84822345991','Khoa Kỹ thuật Y học'),
('CKI XN Đặng Minh Phương','Quản lý thực hành tiền lâm sàng','phuong.dangminh@phenikaa-uni.edu.vn','+84943493668','Khoa Kỹ thuật Y học'),
('CN Trần Thu Trang','Kỹ thuật viên','trang.tranthu@phenikaa-uni.edu.vn','+84358965946','Khoa Kỹ thuật Y học'),
('CN. Quách Thị Hương','Kỹ thuật viên','huong.quachthi@phenikaa-uni.edu.vn','+84385250897','Khoa Kỹ thuật Y học'),
('CN Vũ Thị Minh Châu','KTV - Trợ giảng','chau.vuthiminh@phenikaa-uni.edu.vn','+84971663872','Khoa Kỹ thuật Y học'),
('CN Tạ Thị Kim Liên','KTV - Trợ giảng','Lien.tathikim@phenikaa-uni.edu.vn','+84987081615','Khoa Kỹ thuật Y học'),
('CN Mai Thị Liên','Thư ký','lien.maithi@phenikaa-uni.edu.vn','+84975789839','Khoa Kỹ thuật Y học'),

('PGS.TS Phạm Thiện Ngọc','TBM Hóa - Hóa sinh','Ngoc.phamthien@phenikaa-uni.edu.vn','+84912112292','Khoa Khoa học Y sinh'),
('TS. Trịnh Thị Trang Nhung','Phó Trưởng khoa','nhung.trinhthitrang@phenikaa-uni.edu.vn','+84983275586','Khoa Khoa học Y sinh'),
('ThS Nguyễn Thị Loan','Giảng viên','loan.nguyenthi@phenikaa-uni.edu.vn','+84912280842','Khoa Khoa học Y sinh'),
('ThS Nguyễn Thị Linh Hoa','Giảng viên','hoa.nguyenthilinh@phenikaa-uni.edu.vn','+84375444465','Khoa Khoa học Y sinh'),
('CN Đinh Thị Thanh','Kỹ thuật viên','thanh.dinhthi@phenikaa-uni.edu.vn','+84989850921','Khoa Khoa học Y sinh'),
('TS. Chử Lương Luân','Giảng viên','luan.chuluong@phenikaa-uni.edu.vn','+84985464929','Khoa Khoa học Y sinh'),
('TS. Võ Đình Vinh','TBM Giải phẫu - Mô phôi','vinh.vodinh@phenikaa-uni.edu.vn','+84913237239','Khoa Khoa học Y sinh'),
('PGS.TS. Nguyễn Văn Huy','Phó Trưởng BM Giải phẫu - Mô Phôi','huy.nguyenvan@phenikaa-uni.edu.vn','+84989400627','Khoa Khoa học Y sinh'),
('ThS. Ngô văn Lăng','Giảng viên','lang.ngovan@phenikaa-uni.edu.vn','+84962273390','Khoa Khoa học Y sinh'),
('ThS. Nguyễn Thị Hương','Giảng viên','huong.nguyenthi@phenikaa-uni.edu.vn','+84396980775','Khoa Khoa học Y sinh'),
('ThS. Tăng Thị Kỳ Ninh','Giảng viên','ninh.tangthiky@phenikaa-uni.edu.vn','+84983686677','Khoa Khoa học Y sinh'),
('CN Vũ Thị Vân Anh','Kỹ thuật viên','anh.vuthivan1@phenikaa-uni.edu.vn','+84382436632','Khoa Khoa học Y sinh'),
('PGS.TS. Trần Quang Huy','Phụ trách Bộ môn Sinh lý - Thăm dò chức năng;Phó Viện trưởng Viện Nghiên cứu Nano; Trưởng nhóm nghiên cứu nBIORD Lab','huy.tranquang@phenikaa-uni.edu.vn','+84978960658','Khoa Khoa học Y sinh'),
('ThS Nguyễn Thị Huế','Giảng viên','hue.nguyenthi@phenikaa-uni.edu.vn','+84326541350','Khoa Khoa học Y sinh'),
('PGS.TS. Nguyễn Văn Hưng','TBM Giải phẫu bệnh - Pháp y','hung.nguyenvan@phenikaa-uni.edu.vn','+84988726638','Khoa Khoa học Y sinh'),
('ThS.BSNT Dương Đình Toản','Giảng viên','toan.duongdinh@phenikaa-uni.edu.vn','+84346648189','Khoa Khoa học Y sinh'),
('ThS.BSNT Lê Hải Giang','Giảng viên','giang.lehai@phenikaa-uni.edu.vn','+84975880309','Khoa Khoa học Y sinh'),
('PGS.TS Nguyễn Thị Vinh Hà','TBM Sinh lý bệnh - Miễn dịch','Ha.nguyenthivinh@phenikaa-uni.edu.vn','+84912949697','Khoa Khoa học Y sinh'),
('ThS.BSNT Phùng Thị Thuý','Giảng viên','thuy.phungthi@phenikaa-uni.edu.vn','+84346189145','Khoa Khoa học Y sinh'),
('TS Nguyễn Thị Vân Anh','Giảng viên','anh.nguyenthivan1@phenikaa-uni.edu.vn','+84989695826','Khoa Khoa học Y sinh'),
('TS. Nguyễn Văn Tuấn','Phụ trách Bộ môn Vi sinh - Ký sinh trùng','tuan.nguyenvan2@phenikaa-uni.edu.vn','+84915657944','Khoa Khoa học Y sinh'),
('Đỗ Văn Vũ','Kỹ thuật viên','vu.dovan@phenikaa-uni.edu.vn','+84982815114','Khoa Khoa học Y sinh'),
('Ths. Hà Thị Liên','Giảng viên','lien.hathi@phenikaa-uni.edu.vn','+84869356282','Khoa Khoa học Y sinh'),
('PGS.TS Trần Đức Phấn','Trưởng Bộ môn Y sinh học - Di truyền','phan.tranduc@phenikaa-uni.edu.vn','+84913006877','Khoa Khoa học Y sinh'),
('TS. Đỗ Vân Khanh','Trưởng nhóm nghiên cứu tiềm năng Trưởng PTN Nghiên cứu ứng dụng y sinh;Giảng viên Bộ môn Khoa học thần kinh, Khoa Y','khanh.dovan@phenikaa-uni.edu.vn','+84823394436','Khoa Khoa học Y sinh'),
('TS. Nguyễn Văn Huấn','Giảng viên','huan.nguyenvan@phenikaa-uni.edu.vn','+84819033764','Khoa Khoa học Y sinh'),
('Ths. Đỗ Thị Huê','Giảng viên','hue.dothi@phenikaa-uni.edu.vn','+84988852562','Khoa Khoa học Y sinh'),

('PGS.TS. Mai Đắc Biên','Trưởng khoa','Bien.maidac@phenikaa-uni.edu.vn','+84909707359','Khoa Luật'),
('PGS.TS. Ngô Thị Hường','Phó Trưởng khoa; Trưởng bộ môn Lịch sử và Lý luận Nhà nước & Pháp luật','Huong.ngothi@phenikaa-uni.edu.vn','+84988070864','Khoa Luật'),
('PGS.TS. Nghiêm Xuân Minh','Giảng viên Bộ môn Lịch sử và Lý luận Nhà nước & Pháp luật','Minh.nghiemxuan@phenikaa-unil.edu.vn','+84912159841','Khoa Luật'),
('ThS. Trần Thị Mai','Giảng viên Bộ môn Lịch sử và Lý luận Nhà nước & Pháp luật','Mai.tranthi@phenikaa-uni.edu.vn','+84396222268','Khoa Luật'),
('ThS. Nguyễn Thị Thu Phương','Giảng viên Bộ môn Lịch sử và Lý luận Nhà nước & Pháp luật','Phuong.nguyenthithu@phenikaa-uni.edu.vn','+84912309797','Khoa Luật'),
('TS. Phan Thị Thu Lê','Giảng viên Bộ môn Lịch sử và Lý luận Nhà nước & Pháp luật','le.phanthithu@phenikaa-uni.edu.vn','+84984057618','Khoa Luật'),
('TS. Nguyễn Thái Nhạn','Giảng viên Bộ môn Luật Kinh tế','nhan.nguyenthai@phenikaa-uni.edu.vn','+84914166019','Khoa Luật'),
('TS. Nguyễn Phương Thảo','Giảng viên Bộ môn Luật Kinh tế','Thao.nguyenphuong@phenikaa-uni.edu.vn','+84988394210','Khoa Luật'),
('ThS. Quan Thị Mai Hương','Giảng viên Bộ môn Luật Kinh tế','Huong.quanthimai@phenikaa-uni.edu.vn','+84906116793','Khoa Luật'),
('ThS. Nguyễn Phương Đông','Giảng viên Bộ môn Luật Kinh tế','Dong.nguyenphuong@phenikaa-uni.edu.vn','+84346362967','Khoa Luật'),
('ThS. Lưu Tùng Lâm','Giảng viên Bộ môn Luật Kinh tế','lam.luutung@phenikaa-uni.edu.vn','+84943614196','Khoa Luật'),
('TS. Nguyễn Hồng Bắc','Trưởng Bộ môn Luật Quốc tế và Kinh doanh Quốc tế','Bac.nguyenhong@phenikaa-uni.edu.vn','+84904764784','Khoa Luật'),
('TS. Luật sư Lê Hồng Phúc','Giảng viên Bộ môn Luật Quốc tế và Kinh doanh Quốc tế','Phuc.nguyenhong@phenikaa-uni.edu.vn','+84xxxxxxxxx','Khoa Luật'),
('ThS. Nguyễn Hoàng Anh','Giảng viên Bộ môn Luật Quốc tế và Kinh doanh Quốc tế','anh.nguyenhoang1@phenikaa-uni.edu.vn','+84912178128','Khoa Luật'),
('Cô Phạm Thị Phương Loan','Thư ký Văn phòng Khoa Luật','Loan.phamthiphuong@phenikaa-uni.edu.vn','+84xxxxxxxxx','Khoa Luật'),

('GS.TS. Nguyễn Văn Hiếu','Phó Hiệu trưởng,Trưởng khoa;Hiệu trưởng Trường Kỹ thuật Phenikaa; Trưởng nhóm nghiên cứu mạnh; Giảng viên','hieu.nguyenvan@phenikaa-uni.edu.vn','+84912786572','Khoa Công nghệ số liên ngành'),
('TS. Nguyễn Thị Hạnh','Phó Trưởng khoa','hanh.nguyenthi@phenikaa-uni.edu.vn','+84936572882','Khoa Công nghệ số liên ngành'),
('TS. Nguyễn Việt Anh','Phó Trưởng khoa','anh.nguyenviet2@phenikaa-uni.edu.vn','+84988493374','Khoa Công nghệ số liên ngành'),
('PGS.TS. Phạm Ngọc Dũng','Trưởng Bộ môn Công nghệ tài chính','dung.phamngoc@phenikaa-uni.edu.vn','+84979098999','Khoa Công nghệ số liên ngành'),
('TS. Nguyễn Thị Hằng','Giám đốc chương trình đào tạo, Giảng viên','hang.nguyenthi@phenikaa-uni.edu.vn','+84974773886','Khoa Công nghệ số liên ngành'),
('TS. Hà Thị Hường','Giảng viên','huong.hathi@phenikaa-uni.edu.vn','+84388929252','Khoa Công nghệ số liên ngành'),
('TS. Đặng Thị Huyền','Giảng viên','huyen.dangthi@phenikaa-uni.edu.vn','+84438222157 ','Khoa Công nghệ số liên ngành'),
('TS. Nguyễn Thị Thắm','Giảng viên','tham.nguyenthi@phenikaa-uni.edu.vn','+84975191322','Khoa Công nghệ số liên ngành'),
('ThS. Nguyễn Minh Hiếu','Giảng viên','hieu.nguyenminh1@phenikaa-uni.edu.vn','+84899992355','Khoa Công nghệ số liên ngành'),
('ThS. Đặng Mai Linh','Giảng viên','linh.dangmai@phenikaa-uni.edu.vn','+84962083315','Khoa Công nghệ số liên ngành'),
('ThS. Nguyễn Hoàng Anh','Giảng viên','anh.nguyenhoang@phenikaa-uni.edu.vn','+84936063694','Khoa Công nghệ số liên ngành'),
('ThS. Vũ Phương Thảo','Giảng viên','thao.vuphuong@phenikaa-uni.edu.vn','+84911052772','Khoa Công nghệ số liên ngành'),
('ThS. Đỗ Năng Thắng','Giảng viên','thang.donang@phenikaa-uni.edu.vn','+84914819586','Khoa Công nghệ số liên ngành'),
('ThS. Lê Ngọc Lam','Giảng viên','lam.lengoc@phenikaa-uni.edu.vn','+84383434151','Khoa Công nghệ số liên ngành'),
('ThS. Hà Thị Cẩm Lệ','Giảng viên','le.hathicam@phenikaa-uni.edu.vn','+84901700900','Khoa Công nghệ số liên ngành'),
('ThS. Ngô Anh Thái','Giảng viên','thai.ngoanh@phenikaa-uni.edu.vn','+84355001111','Khoa Công nghệ số liên ngành'),
('ThS. Phan Thị Thanh Huệ','Giảng viên','hue.phanthithanh@phenikaa-uni.edu.vn','+84973888255','Khoa Công nghệ số liên ngành'),
('ThS. Nguyễn Tuấn Linh','Thư ký khoa','linh.nguyentuan@phenikaa-uni.edu.vn','+84376726869','Khoa Công nghệ số liên ngành'),

('PGS. TS. Đỗ Quang Trung','Trưởng Khoa','trung.doquang@phenikaa-uni.edu.vn','+84579908882','Khoa Khoa học cơ bản'),
('PGS. TS. Nguyễn Tư','Phó Trưởng Khoa','tu.nguyen@phenikaa-uni.edu.vn','+84843454686','Khoa Khoa học cơ bản'),
('GS. TS. Phùng Văn Đồng','Viện trưởng - Viện nghiên cứu tiên tiến Phenikaa (PIAS); Trưởng nhóm nghiên cứu mạnh','dong.phungvan@phenikaa-uni.edu.vn','+84979347143','Khoa Khoa học cơ bản'),
('GS. TS. Trần Hoài Nam','Phó viện trưởng - Viện nghiên cứu tiên tiến Phenikaa (PIAS)','nam.tranhoai@phenikaa-uni.edu.vn','+84978060069','Khoa Khoa học cơ bản'),
('PGS. TS. Dư Thị Xuân Thảo','Giảng viên Bộ môn Vật lý','thao.duthixuan@phenikaa-uni.edu.vn','+84885934611','Khoa Khoa học cơ bản'),
('TS. Dương Văn Lợi','Giảng viên Bộ môn Vật lý','loi.duongvan@phenikaa-uni.edu.vn','+84982342904','Khoa Khoa học cơ bản'),
('TS. Ngô Hải Tân','Giảng viên Bộ môn Vật lý','tan.ngohai@phenikaa-uni.edu.vn','+84969608401','Khoa Khoa học cơ bản'),
('TS. Cao Hoàng Nam','Giảng viên Bộ môn Vật lý','nam.caohoang@phenikaa-uni.edu.vn','+84867712273','Khoa Khoa học cơ bản'),
('PGS.TS. Lê Đức Ninh','Giảng viên Bộ môn Vật lý','ninh.leduc@phenikaa-uni.edu.vn','+84832754249','Khoa Khoa học cơ bản'),
('TS. Đào Thị Nhung','Giảng viên Bộ môn Vật lý','nhung.daothi@phenikaa-uni.edu.vn','+84xxxxxxxxx','Khoa Khoa học cơ bản'),
('TS. Bùi Thị Hạnh','Giảng viên Bộ môn Vật lý','hanh.buithi@phenikaa-uni.edu.vn','+84384276839','Khoa Khoa học cơ bản'),
('TS. Nguyễn Văn Du','Giảng viên Bộ môn Vật lý','du.nguyenvan@phenikaa-uni.edu.vn','+84682417874','Khoa Khoa học cơ bản'),
('PGS.TS. Nguyễn Ngọc Anh','Giảng viên Bộ môn Vật lý','anh.nguyenngoc1@phenikaa-uni.edu.vn','+84xxxxxxxxx','Khoa Khoa học cơ bản'),
('ThS. Trần Minh Tiến','Giảng viên Bộ môn Vật lý','tien.TranMinh@phenikaa-uni.edu.vn','+84915786265','Khoa Khoa học cơ bản'),
('TS. Phan Quang Sáng','Trưởng Bộ môn Toán','sang.phanquang@phenikaa-uni.edu.vn','+84389923682','Khoa Khoa học cơ bản'),
('TS. Vũ Hữu Nhự','Giảng viên Bộ môn Toán','nhu.vuhuu@phenikaa-uni.edu.vn','+84943125855','Khoa Khoa học cơ bản'),
('TS. Trần Duy','Giảng viên Bộ môn Toán','duy.tran@phenikaa-uni.edu.vn','+84xxxxxxxxx','Khoa Khoa học cơ bản'),
('TS. Trần Mạnh Hùng','Giảng viên Bộ môn Toán','hung.tranmanh@phenikaa-uni.edu.vn','+84xxxxxxxxx','Khoa Khoa học cơ bản'),
('TS. Bùi Xuân Quang','Giảng viên Bộ môn Toán','quang.buixuan@phenikaa-uni.edu.vn','+84902126121','Khoa Khoa học cơ bản'),
('TS. Dương Ngọc Sơn','Giảng viên Bộ môn Toán','son.duongngoc@phenikaa-uni.edu.vn','+84913666288','Khoa Khoa học cơ bản'),
('TS. Nguyễn Thị Loan','Giảng viên Bộ môn Toán','loan.nguyenthi2@phenikaa-uni.edu.vn','+84474066069','Khoa Khoa học cơ bản'),
('TS. Trần Quang Tuệ','Giảng viên Bộ môn Toán','tue.tranquang@phenikaa-uni.edu.vn','+84979825640','Khoa Khoa học cơ bản'),
('ThS. Nguyễn Đức Ngà','Giảng viên Bộ môn Toán','nga.nguyenduc@phenikaa-uni.edu.vn','+84973811856','Khoa Khoa học cơ bản'),
('TS. Nguyễn Thị Ngọc Anh','Giảng viên Bộ môn Toán','anh.nguyenthingoc3@phenikaa-uni.edu.vn','+84637353830','Khoa Khoa học cơ bản'),
('TS. Phạm Bá Đức','Giảng viên Bộ môn Toán','duc.phamba@phenikaa-uni.edu.vn','+84xxxxxxxxx','Khoa Khoa học cơ bản'),
('TS.Đỗ Khánh Chi','Giảng viên Bộ môn Lý luận chính trị','chi.dokhanh@phenikaa-uni.edu.vn','+84322159677','Khoa Khoa học cơ bản'),
('TS. Đồng Thị Tuyền','Giảng viên Bộ môn Lý luận chính trị - Pháp luật','tuyen.dongthi@phenikaa-uni.edu.vn','+84985898672','Khoa Khoa học cơ bản'),
('ThS. Nguyễn Thị Điểm','Trưởng Bộ môn Giáo dục thể chất','diem.nguyenthi@phenikaa-uni.edu.vn','+84915319139','Khoa Khoa học cơ bản'),
('ThS.Nguyễn Trung Hạnh','Giảng viên Bộ môn Giáo dục thể chất','hanh.nguyentrung@phenikaa-uni.edu.vn','+84376912345','Khoa Khoa học cơ bản'),
('ThS. Trần Hữu Trung','Giảng viên Bộ môn Giáo dục thể chất','trung.tranhuu@phenikaa-uni.edu.vn','+84899588869','Khoa Khoa học cơ bản'),
('ThS. Nguyễn Văn Căn','Giảng viên Bộ môn Giáo dục thể chất','can.nguyenvan@phenikaa-uni.edu.vn','+84585940000','Khoa Khoa học cơ bản'),
('ThS. Nghiêm Thị Tuyết','Thư ký/Giáo vụ Khoa','tuyet.nghiemthi@phenikaa-uni.edu.vn','+84387765966','Khoa Khoa học cơ bản'),
('CN. Đinh Thị Thanh Nhàn','Thư ký/Giáo vụ Khoa','nhan.dinhthithanh@phenikaa-uni.edu.vn','+84xxxxxxxxx','Khoa Khoa học cơ bản')

),
cleaned AS (
  SELECT
    trim(name)                         AS name,
    trim(position)                     AS position,
    lower(NULLIF(trim(email), ''))     AS email_raw,        -- '' -> NULL; lowercase
    lower(                               -- đưa 'X' -> 'x'
      regexp_replace(                   -- bỏ mọi khoảng trắng nội bộ
        COALESCE(trim(phone), ''),
        '\s+', '', 'g'
      )
    )                                  AS phone_clean,
    faculty_name
  FROM src
),
norm AS (
  SELECT
    name,
    position,
    -- email hợp lệ thì giữ, không hợp lệ -> NULL
    CASE
      WHEN email_raw ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$' THEN email_raw
      ELSE NULL
    END AS email,
    -- GIỮ nguyên phone (kể cả có 'x'); nếu rỗng mới đưa về NULL
    NULLIF(phone_clean, '') AS phone,
    faculty_name
  FROM cleaned
)
INSERT INTO miscore_lecturer
  (faculty_id, school_id, name, position, email, phone, is_active, created_at, updated_at)
SELECT
  f.id, f.school_id,
  n.name, n.position, n.email, n.phone,
  TRUE, now(), now()
FROM norm n
JOIN miscore_faculty f
  ON regexp_replace(f.name,'[–—-]+','-','g') = regexp_replace(n.faculty_name,'[–—-]+','-','g')
ON CONFLICT (email) DO UPDATE
SET name       = EXCLUDED.name,
    position   = EXCLUDED.position,
    phone      = EXCLUDED.phone,
    faculty_id = EXCLUDED.faculty_id,
    school_id  = EXCLUDED.school_id,
    updated_at = now();